### DISCUSSION TITLE
Is it possible to configure a pod to spin up containers on the host machine?

### DISCUSSION THREAD

**Discussion by artburkart** [bottlerocket-os/bottlerocket#1840] [Q&A] [answered]
I'm struggling to prove out an example where I make a container in a Kubernetes pod spin up another container on a host machine running Bottlerocket. Naturally, some variation of it is possible using the "admin" and "control" containers, but I'm starting to wonder whether it's possible in the context of Kubernetes.

Thanks for your help!

UPDATE:
The question I should've asked was whether I could use _ctr_ to create a container inside of a container on Bottlerocket.

**Comment by bcressey** [comment, marked as answer]
You can map in the host's `/usr/bin/apiclient` and `/run/api.sock` to a privileged pod, then use the settings API to start a static pod:
```
apiclient set \
  kubernetes.static-pods.my-pod.manifest=${BASE64_BLOB} \
  kubernetes.static-pods.my-pod.enabled=true
```

kubelet will register the static pod as a mirror pod when it connects to the Kubernetes API server.

To create a "real" pod, you'd need to run your pod with a service account and role that allowed pod creation. I haven't tried this, but I expect the role would be something like the [pod-reader](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-example) example with mutating verbs added.

**Reply by artburkart** [reply]
Oh, interesting. Thanks for the insight. It sounds like it's possible to spin up a pod, so maybe it's possible to spin up a container using _containerd_?

**Reply by artburkart** [reply]
To prove out a tiny use case, I'm trying to [get this code](https://containerd.io/docs/getting-started/#pulling-the-redis-image) working in a Kubernetes pod. So far, no luck. This is my pod manifest:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2021-11-23T01:55:23Z"
  labels:
    app: test
    release: test
    statefulset.kubernetes.io/pod-name: test
  name: test
  namespace: default
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: test-worker
              release: test
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - args:
    - sleep
    - "10000"
    image: golang:bullseye
    imagePullPolicy: IfNotPresent
    name: test-worker
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /run/containerd/containerd.sock
      name: containerd-sock
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: test-worker-0
  nodeName: ip-REDACTED.us-east-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /run/host-containerd/containerd.sock
      type: Socket
    name: containerd-sock
```

So far, I get this error:

```
2021/11/23 15:42:20 failed to mount /tmp/containerd-mount2991968635: no such file or directory
exit status 1
```

One thing I'm not sure of is whether I've mounted the correct _containerd_ socket. From the "admin" container, I was able to see a socket at `/run/host-containerd/containerd.sock`, so I mounted that, but maybe that's wrong. ¯\_(ツ)_/¯

**Reply by bcressey** [reply]
Yup, it's also possible to start a container using the containerd socket.

I tried out an edited version of your manifest and it worked for me:
```
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
  - args:
    - sleep
    - "10000"
    image: golang:bullseye
    imagePullPolicy: IfNotPresent
    name: foo-container
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /run/containerd/containerd.sock
      name: containerd-sock
  volumes:
  - hostPath:
      path: /run/host-containerd/containerd.sock
      type: Socket
    name: containerd-sock
```

```
❯ kubectl exec -it foo -- /bin/sh
# ls -latr /run/containerd/containerd.sock
srw-rw----. 1 root root 0 Nov 19 00:01 /run/containerd/containerd.sock
```

Is it possible that the pod got scheduled on a non-Bottlerocket node? That containerd socket path is pretty specific to Bottlerocket and wouldn't work elsewhere.
