### DISCUSSION TITLE
Problems with XFS volumes on some provisioners

### DISCUSSION THREAD

**Discussion by vadimgusev-codefresh** [bottlerocket-os/bottlerocket#2202] [Q&A] [answered]
Hi, initially I've encountered this problem with our proprietary storage provisioner after switching from `AL2` AMIs to `Bottlerocket`, but I was able to replicate the issue on the mainstream EKS provisioners.

Those are 2 `StorageClasses` I've defined:

```yaml
# WORKS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-csi-xfs
parameters:
  type: gp3
  fsType: xfs
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
# DOESN'T WORK
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-xfs
parameters:
  type: gp2
  fsType: xfs
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

When I spin up pod+pvc referring those SCs, the `ebs-csi-xfs` works just fine while `gp2-xfs` throws me an error in pod events:
```
Warning  FailedMount             2s (x3 over 5s)    kubelet 
MountVolume.MountDevice failed for volume "pvc-50cf42d9-2bec-4d95-acde-950400d044ba" : format of disk "/dev/nvme2n1" failed: type:("xfs") target:("/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/us-east-1a/vol-0636ee72044526891") options:("defaults") errcode:(executable file not found in $PATH) output:()
```
as if it expects host machine to have `mkfs.xfs` or similar tool to format the partition.

What can I do to further investigate and hopefully resolve the issue? Thanks!
