### DISCUSSION TITLE
`settings.container-registry.credentials` not working as expected

### DISCUSSION THREAD

**Discussion by BenB196** [bottlerocket-os/bottlerocket#2514] [Q&A] [answered]
Hi All,

I'm hoping someone might be able to help. I'm trying to implement: https://github.com/bottlerocket-os/bottlerocket/discussions/1618 via a custom container image. I'm using a self-hosted GitLab instance container registry, and am using AWS EKS managed node group with the Bottlerocket AMI (`1.23`). I'm seeing the newly created Bottlerocket node contact the container registry, but I'm only seeing `401`s on GitLab end. I've validated that the username/password work directly, so not sure where I have a configuration issue. The docs seem a bit spare in this area, so wondering if anyone can spot an error/issue in my configuration.

Userdata addition:

```toml
[[settings.container-registry.credentials]]
registry = "gitlab.domain.com:5050/bottlerocket-os-ephemeral-disk"
username = "bottlerocket-image"
password = "<snipped>"
[settings.bootstrap-containers.setup-ephemeral-disks]
source = "gitlab.domain:5050/bottlerocket-os-ephemeral-disk:latest-xfs"
mode = "always"
essential = true
```
