### DISCUSSION TITLE
Joining a self-managed autoscaling group nodes (not using node groups) to an EKS cluster

### DISCUSSION THREAD

**Discussion by moshe0076** [bottlerocket-os/bottlerocket#4263] [Q&A]
Hello,

When working with Amazon Linux OS-based nodes, we can use the ```/etc/eks/bootstrap.sh``` script to bootstrap a node (running in a self-managed autoscaling group, not using node groups) to join an EKS cluster. I was wondering if this is also possible with Bottlerocket OS-based nodes? Do I use the ```bootstrap.sh``` or the ```settings.kubernetes.*``` instead? If ```settings.kubernetes.*``` is the way to go, what are the parameters that need to be added to the user data in a CloudFormation/CDK stack?

Thanks!

**Comment by cbgbt** [comment]
Hello,

I often do this via `settings.kubernetes.*` by applying userdata like the following:


```toml
[settings.kubernetes]

# Kubernetes Control Plane API Endpoint
api-server = "https://API_SERVER_HOSTNAME"

# Kubernetes Cluster CA Certificate
cluster-certificate = "INSERT_CLUSTER_CERT"

# Kubernetes Cluster Name
cluster-name = "INSERT_CLUSTER_NAME"
```

Hope that helps! Let me know if you have any questions.
