### ISSUE TITLE
eksctl sample yaml fails with arm64 nodegroup

### ISSUE THREAD

**Issue by scottmalkie** [bottlerocket-os/bottlerocket#1096]
**Image I'm using:**
k8s 1.17 arm64 variant

**What I expected to happen:**
Simply swapping m5.large to m6g.medium should pull the correct AMI for bottlerocket 1.17
eksctl itself supports ARM: https://eksctl.io/usage/arm-support/

**What actually happened:**
`amiFamily: Bottlerocket` always pulls x86_64 image (currently ami-066950977806aa4f7)

**How to reproduce the problem:**
run the `sample-eksctl.yaml` in the QUICKSTART-EKS replacing m5.large with m6g.medium (line 12)
https://github.com/bottlerocket-os/bottlerocket/blob/develop/sample-eksctl.yaml

It works if you manually override the AMI by adding the ami-id (pulled from SSM) 
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket
  region: us-west-2
  version: '1.17'

nodeGroups:
  - name: ng-bottlerocket
    ami: ami-0f8df7ebc1e6ea31d
    instanceType: m6g.medium
    amiFamily: Bottlerocket
    desiredCapacity: 4
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    bottlerocket:
      settings:
        motd: "Hello from eksctl arm64!"
```
