### ISSUE TITLE
MySQL 5.7 container OOM kill / changing the NOFILE limit

### ISSUE THREAD

**Issue by zlangbert** [bottlerocket-os/bottlerocket#1136]
I am running a 1.17 EKS cluster that was we recently tried to switch to bottlerocket nodes. We ran into an issue where MySQL 5.7 containers were being OOM killed. This does not happen on the latest AL2 EKS AMI. 

After some searching I came across these issues / PRs:
https://github.com/docker-library/mysql/issues/579
https://github.com/kubernetes-sigs/kind/pull/760
https://github.com/containerd/containerd/issues/3201
https://github.com/containerd/containerd/pull/3202 (this one has since been [reverted](https://github.com/containerd/containerd/commit/c691c36614622b205a859ae7e656badb4a553076#diff-5f2ec709a3860c8863a703cffa7b4921) without addressing the reason it was changed in the first place)

I am having trouble actually testing this change on bottlerocket, but it appears that setting [LimitNOFILE](https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/containerd/containerd.service#L17) to something like `1048576` should fix this issue.

I also found that the `mysql:8` image does not exhibit this issue.

So couple questions:
1. This doesn't seem like a bottlerocket bug necessarily, but wanted to at least report the issue and see if it something that could be addressed, especially given the behavior change compared to the AL2 EKS AMI.
2. Is there any friendly way of making that kind of modification to the containerd unit file without rebuilding the image myself? Even on an already running box I was having trouble trying to test this because I couldn't find a way to edit the file after `sudo sheltie`

**What I expected to happen:**
I would expect the mysql container to start and use a resonable amount of memory.

**What actually happened:**
The mysql container attempts to consume many gigabytes of ram and is OOM killed when there are resource limits placed on it.

**How to reproduce the problem:**

Run an EKS cluster with bottlerocket nodes and apply this manifest. The mysql pod will go into a restart loop being OOM killed over and over. If you remove the resource limits you can see the pod will take up to 16gb of RAM doing nothing.

```
apiVersion: v1
kind: Pod
metadata:
  name: mysql-test
  namespace: default
spec:
  containers:
    - name: mysql
      imagePullPolicy: Always
      image: 'mysql:5.7'
      env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: test
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 300Mi
```

**Image I'm using:**
bottlerocket 1.0.1 / x86_64 in us-west-2 - `ami-0d222c28fd8edb9ff`
