### ISSUE TITLE
How can I run docker build in a container running on Bottlerocket?

### ISSUE THREAD

**Issue by tomfotherby** [bottlerocket-os/bottlerocket#1189]
We have a EKS cluster and are investigating whether we can move from _Amazon Linux 2_ to **Bottlerocket**. We are trying to figure out how to run a `docker build` from a container in our Bottlerocket node. I understand Bottlerocket uses a different container runtime than _Amazon Linux 2_ and I'd like some advice on how to use it in a similar way, at a Pod level.

This is a Pod that works in our _Amazon Linux 2_ Nodes and can be used to show our migration problem:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
    - name: debug
      image: docker:19.03
      command: ["bin/sh", "-c", "sleep 36000"]
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
```

With this pod I can do:

`$ kubectl exec -it test1 -- docker images`

and I get a list of docker images on this Node. I can also build a new docker image, for example:

```
$ kubectl exec -it test1 -- sh
$ echo -e "FROM alpine\nRUN echo hi" | docker build --quiet -t buildtest -
sha256:7c1b0e708a13ffd84ae144ac1dc683751120241a4e51495715d7d6b45f892e23
```

But if I try the same in _Bottlerocket_:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test3
spec:
  # Schedule this Pod on our BottleRocket test Node
  nodeSelector:
    nodegroup: bottlerocket-node
  tolerations:
    - key: workload
      value: bottlerocket-only
      operator: Equal
      effect: NoSchedule
  containers:
    - name: debug
      image: docker:19.03
      command: ["bin/sh", "-c", "sleep 36000"]
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
```

The Pod wont start with Error:

> MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file

After Googling for a solution, I came across "dockershim" ([ref](https://github.com/bottlerocket-os/bottlerocket/issues/747)). I don't yet understand what "dockershim" is (maybe someone can point me to some documentation?) But I tried using it by mounting the host `/run/dockershim.sock` socket to the container docker socket like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test5
spec:
  # Schedule this Pod on our BottleRocket test Node
  nodeSelector:
    nodegroup: bottlerocket-node
  tolerations:
    - key: workload
      value: bottlerocket-only
      operator: Equal
      effect: NoSchedule
  containers:
    - name: debug
      image: docker:19.03
      command: ["bin/sh", "-c", "sleep 36000"]
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /run/dockershim.sock
        type: Socket
```

This time the Pod starts but I get a error using docker. I've used the `docker images` command to demonstrate the error:

```
$ kubectl exec -it test5 -- docker images 
Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/json: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x00\x04\x00\x00\x00\x00\x00".
* Are you trying to connect to a TLS-enabled daemon without TLS?
command terminated with exit code 1
```

I tried a few other incarnations, but had no luck figuring out a solution.

Does anyone know how I can run `docker images` from within a Pod on BottleRocket? (I think if `docker images` works, then `docker build` should also work) Or maybe I'm asking for something that's not possible? If so, I'm obviously missing the architectural picture of how a non-docker container runtime works. If there is a good resource I can read for this, please let me know.

This is the first time I've used SELinux - Maybe it is relevant?

---

I'm using Bottlerocket `ami-00e1ed6a3ebe06fd0` on EKS `v1.18.8`
