### ISSUE TITLE
Replicaset does not create put with unsafe sysctls even with allowed-unsafe-sysctls = ["net.core.somaxconn"]

### ISSUE THREAD

**Issue by AhmadMS1988** [bottlerocket-os/bottlerocket#1499]
**Image I'm using:**
aws-k8s-1.19, AMI: ami-04269f2e9be10beeb
The cluster is a mix of amazon linux 2 and bottlerocket, but the pod has node selector with a lable that only on bottlerocket nodegroup

**What I expected to happen:**
When configuring with allowed-unsafe-sysctls = ["net.core.somaxconn"] in the userdata, 
The scheduling of a podspec with this configs should work:
securityContext:
        sysctls:
          - name: net.core.somaxconn
            value: "1024"

**What actually happened:**
The replica set failed to schedule the pods with creating pods failing due to Sysctl Forbidden

Please your guidance on how to investigate and solve the issue.

**Comment by jhaynes** [comment]
@AhmadMS1988 Thanks for opening this issue. We're looking into it!

**Comment by srgothi92** [comment]
Thanks for opening the issue ! I got the same "**forbidden... "net.core.somaxconn" is not allowed "** error when I tried below sample deployment with `allowed-unsafe-sysctls = ["net.core.somaxconn"]` in the `userdata`.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unsafe-sysctl-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      securityContext:
        sysctls:
        - name: net.core.somaxconn
          value: "1024"
```
However, according the docs [here](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#podsecuritypolicy), you’ll need to also add the sysctl parameter in a custom pod security policy. I tried a slightly modified default [eks.privileged](https://docs.aws.amazon.com/eks/latest/userguide/pod-security-policy.html) policy, which includes `allowedUnsafeSysctls` and I was able to start the same deployment. I just added below lines in default eks.privileged pod security policy.
```yaml
 spec:
   allowedUnsafeSysctls:
     - net.core.somaxconn
```
I think it might be the same issue for you, let me know if you face an issue even after allowing it in the Pod Security Policy.
