### ISSUE TITLE
Need a way to deploy Bottlerocket nodes with a larger data volume

### ISSUE THREAD

**Issue by st33v** [bottlerocket-os/bottlerocket#1604]
I'm deploying bottlerocket using terraform, not eksctl, by using [this module](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/bottlerocket). The AMI comes with a very small data volume-- 20Gb on xvdb.

I realize this project doesn't support terraform modules but this team is probably the best source for advice on this matter. And all terraform aside, it seems like eksctl is the ONLY way to resize the data volume. 

**What I'd like:**
I'd like some advice as to how I can update the module to resize the volume... I see that eksctl can modify the size of the data volume, but HOW? Terraform can't manage what it doesn't create, so how is eksctl different?  Is there anything in an AWS launch config that I can add to make xvdb larger? I can increase the root volume size easily enough so why not xvdb? Are there bottlerocket images published that DO NOT have the data volume included in the AMI? If so, then I can easily attach a larger data volume in the launch config.

**Any alternatives you've considered:**
I've considered:
a) creating my own AMIs with a larger volume or none at all and attaching one in terraform.
b) possibly using the community supported eksctl provider in terraform 
c) not using bottlerocket

**Comment by tjkirch** [comment]
Hi @st33v!  I recently did this using CloudFormation to create a launch template that changes the block device size.  Launch templates are nice in that you can specify just the properties you want to override, without having to reiterate all the details.  (If you're using launch configs, it's worth switching to launch templates.)

Here's what I did, with the application-specific stuff snipped out:

```yaml
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvdb
            Ebs:
              VolumeSize: 200
              VolumeType: gp2
```

Terraform has an [aws_launch_template resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template) that supports the `volume_size` parameter, so I think you could do the same thing there, and then launch your instances using the launch template.
