### ISSUE TITLE
Unable to change pod's timezone due to read-only file system

### ISSUE THREAD

**Issue by sparkcatalyst96** [bottlerocket-os/bottlerocket#1969]
Hello! We're currently using **Amazon Linux 2 EC2s** on our **EKS** cluster and want to review Bottlerocket as a potential replacement due to it's added security and performance. On all K8s deployments we are **changing the default timezone (UTC) to CET via mounting the /usr/share/zoneinfo/CET path from the host to /etc/zoneinfo**, so that all logging is done in CET timezone, as such:

```
apiVersion: apps/v1beta1
kind: Deployment
spec:
  replicas: 1
    spec:
      containers:
        - name: myContainer
          image: myContainer
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
           path: /usr/share/zoneinfo/CET
```
(other irrelevant yaml settings omitted for clarity, this might not be a valid Deployment definition)

Nodegroup eksctl definition:

```
  - name: ng-bottlerocket
    labels: { type: small }
    amiFamily: Bottlerocket
    instanceType: t3.small
    desiredCapacity: 1
    availabilityZones: ["eu-north-1b"]
    bottlerocket:
      enableAdminContainer: true
      settings:
        kubernetes:
          system-reserved:
            cpu: "50m"
            memory: "50Mi"
          kube-reserved:
            cpu: "50m"
            memory: "50Mi"
          eviction-hard:
            "memory.available": "5%"
        ntp:
          time-servers: ["0.se.pool.ntp.org", "1.se.pool.ntp.org", "2.se.pool.ntp.org", "3.se.pool.ntp.org"]
```

**Image I'm using:**
Bottlerocket-eks-1.21

**What I expected to happen:**
I expect that the /usr/share/zoneinfo/CET path is mounter and the **date** command shows the CET time. This is what happens with Amazon Linux 2 nodegroups.
 

**What actually happened:**
All pods fail to start due to 
`Error: failed to generate container "CONTAINER_ID_HERE" spec: failed to generate spec: failed to mkdir "/usr/share/zoneinfo/CET": mkdir /usr/share/zoneinfo: read-only file system`

**How to reproduce the problem:**
Deploy the Deployment file above on an EKS cluster running K8s 1.21 and a nodegroup with the above eksctl definition

The [documentation](https://github.com/bottlerocket-os/bottlerocket) specifies the bottlerocket.settings.ntp.time-servers option, but since containers do not inherit the host's timezone, this has no effect on the default timezone inside the Debian containers (UTC)

I did not find any setting which would allow the pod to mount the /usr/share/zoneinfo path or to make the filesystem writeable. How do you recommend working around the issue described above? Thanks!
