### ISSUE TITLE
cargo make test for aws-k8s upgrade-downgrade testing

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#2149]
Support upgrade-downgrade testing for aws-k8s variants.

It should be possible to run either the conformance testing, upgrade-downgrade testing, or both.

pubsys gets update repository URLs from Infra.toml. We should also use these values for `cargo make test` for upgrade-downgrade testing.

```toml
[repo.default]
metadata_base_url = "https://updates.bottlerocket.aws/2020-07-07/"
targets_url = "https://updates.bottlerocket.aws/targets/"
```
