### ISSUE TITLE
Allow rootless containers to bind privileged ports and ping

### ISSUE THREAD

**Issue by vflaux** [bottlerocket-os/bottlerocket#2466]
**What I'd like:**
Add config options to allow containers to bind privileged ports (<1024) and open icmp echo sockets without being root.  (This the defaults with dockerd)
It can be enabled within containerd config (/etc/containerd/config.toml).
For kubernetes:
```
[plugins."io.containerd.grpc.v1.cri"]
enable_unprivileged_ports = true
enable_unprivileged_icmp = true
```

**Any alternatives you've considered:**

This can be worked around with kubernetes (>1.22) with a SecurityContext on pods:
```
securityContext:
  sysctls:
    - name: net.ipv4.ip_unprivileged_port_start
      value: "0"
    - name: net.ipv4.ping_group_range
      value: "0 2147483647"
```

It can also be configured within a bootstrap container but I'm not sure how to restart containerd from there.
