### ISSUE TITLE
Kubelet volume relabel fails for Dynatrace OneAgent CSI volumes

### ISSUE THREAD

**Issue by baichinger** [bottlerocket-os/bottlerocket#2556]
**Image I'm using:**
Bottlerocket OS 1.10.1 (aws-k8s-1.23)

**What I expected to happen:**
Dynatrace OneAgent CSI volumes work on Bottlerocket.

**What actually happened:**
1. Dynatrace OneAgent CSI driver successfully mounts the volume to the pod:
    ```
    {"level":"info","ts":"2022-11-07T08:39:07.861Z","logger":"csi-driver","msg":"GRPC call","method":"NodePublishVolume","volume-id":"csi-1f0a5b5faf0aa280913d7a16ab0023393ec52aa563886dc7eebfdef711c13ca4"}
    {"level":"info","ts":"2022-11-07T08:39:07.861Z","logger":"csi-driver","msg":"publishing volume","csiMode":"app","target":"/var/lib/kubelet/pods/174ca84d-4ed5-4c9b-8f09-ce397f5c07a3/volumes/kubernetes.io~csi/oneagent-bin/mount","fstype":"","readonly":false,"volumeID":"csi-1f0a5b5faf0aa280913d7a16ab0023393ec52aa563886dc7eebfdef711c13ca4","attributes":{"csi.storage.k8s.io/ephemeral":"true","csi.storage.k8s.io/pod.name":"pause","csi.storage.k8s.io/pod.namespace":"default","csi.storage.k8s.io/pod.uid":"174ca84d-4ed5-4c9b-8f09-ce397f5c07a3","csi.storage.k8s.io/serviceAccount.name":"default","dynakube":"pup86408-application-monitoring","mode":"app"},"mountflags":[]}
    ```
2. Kubelet tries to relabel the files and fails:
    ```
    Error: failed to generate container "d3408d8e5fbc55df1769265072ade6c67c6a7176bafdae267f4fff904fdb7844" spec: failed to generate spec: relabel "/var/lib/kubelet/pods/174ca84d-4ed5-4c9b-8f09-ce397f5c07a3/volumes/kubernetes.io~csi/oneagent-bin/mount" with "system_u:object_r:data_t:s0:c65,c249" failed: lsetxattr /var/lib/kubelet/pods/174ca84d-4ed5-4c9b-8f09-ce397f5c07a3/volumes/kubernetes.io~csi/oneagent-bin/mount/agent/bin: permission denied
    ```
3. Pod is blocked from starting up with status `Init:CreateContainerError`.

**Additional nodes:**
* SELinux context of files on disk: system_u:object_r:local_t:s0
* SELinux context of operator processes: system_u:system_r:control_t:s0
* Desired SELinux context kubelet wants to enforce: system_u:object_r:data_t:s0
* Related issue: https://github.com/bottlerocket-os/bottlerocket/issues/2218
* CSI driver manifest: https://github.com/Dynatrace/dynatrace-operator/blob/v0.9.1/config/deploy/kubernetes/kubernetes-all.yaml#L4808-L5086

**How to reproduce the problem:**
1. Create a Dynatrace free trial account: https://www.dynatrace.com/trial/
2. Deploy Dynatrace Operator: https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring/set-up-k8s-monitoring-helm
3. Configure `applicationMonitoring`:
    ```
    apiVersion: dynatrace.com/v1beta1
    kind: DynaKube
    metadata:
      name: application-monitoring
    spec:
      apiUrl: https://ENVIRONMENTID.live.dynatrace.com/api
      oneAgent:
        applicationMonitoring:
          useCSIDriver: true
    ```
5. Deploy a K8s pod to a Bottlerocket instance:
    ```
    kind: Pod
    apiVersion: v1
    metadata:
      name: pause
    spec:
      containers:
        - name: pause
          image: k8s.gcr.io/pause:3.1
    ```
6. Observe the pod failing by inspecting its events:
    ```
    ❯ k get pods pause
    NAME    READY   STATUS                      RESTARTS   AGE
    pause   0/1     Init:CreateContainerError   0          98s
    ```
    ```
    ❯ k describe pod pause
    Events:
      Type     Reason     Age                  From               Message
      ----     ------     ----                 ----               -------
      Normal   Scheduled  2m28s                default-scheduler  Successfully assigned default/pause to ip-172-31-34-110.ec2.internal
      Warning  Failed     2m28s                kubelet            Error: failed to generate container "d5473948bd9728c3174cce919fa9f4ce811a75c5a9619e162a2b4946cec65968" spec: failed to generate spec: relabel "/var/lib/kubelet/pods/450a7bbe-87f7-4055-9a65-f6e205826644/volumes/kubernetes.io~csi/oneagent-bin/mount" with "system_u:object_r:data_t:s0:c434,c580" failed: lsetxattr /var/lib/kubelet/pods/450a7bbe-87f7-4055-9a65-f6e205826644/volumes/kubernetes.io~csi/oneagent-bin/mount/agent: permission denied
    ```
