### ISSUE TITLE
Support env in `CredentialProviderConfig`

### ISSUE THREAD

**Issue by samjo-nyang** [bottlerocket-os/bottlerocket#2602]
**What I'd like:**
Hi, I'd like to add some custom environment variables to the credential provider config, such as
```toml
[settings.kubernetes.credential-providers.samjo-credential-provider]
enabled = true
cache-duration = "30m"
image-patterns = ["samjo.private.registry"]

[settings.kubernetes.credential-providers.samjo-credential-provider.env]
my-env = "1"
```
and it transforms into the following.
```yaml
apiVersion: kubelet.config.k8s.io/v1alpha1
kind: CredentialProviderConfig
providers:
  - name: samjo-credential-provider
    matchImages:
      - "samjo.private.registry"
    defaultCacheDuration: "30m"
    apiVersion: credentialprovider.kubelet.k8s.io/v1alpha1
    env:
      - name: MY_ENV
        value: "1"
```

Also, I have a question of the following line - how does this work?
https://github.com/bottlerocket-os/bottlerocket/blame/develop/packages/kubernetes-1.24/credential-provider-config-yaml#L18

Since the line is in the "#each" context on line 5, should it be `../settings.aws.profile`?

**Any alternatives you've considered:** (nothing)
