### ISSUE TITLE
Document how to configure networking for vsphere variant

### ISSUE THREAD

**Issue by faxioman** [bottlerocket-os/bottlerocket#2668]
**What I'd like:**
I'm unable to find how to add a static ip to a vsphere node.
I know I can use net.toml in bare metal provisioning but what about vsphere?

**Any alternatives you've considered:**
I could use the setting settings.boot.kernel-parameters but I cannot find if this is parsed by the vsphere variant and how to set the network parameters.

**Comment by stmcginnis** [comment]
Hey @faxioman, thanks for raising this. I tried searching the docs too, and you are absolutely correct that this needs to be better documented.

I'm trying to find someone that has more experience with VMware setup and deployment, but I _think_ what you can do is a combination of the [OVF `import.spec` instructions in the VMware quickstart docs](https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-VMWARE.md#upload-the-ova) and the networking [configuration instructions for bare metal docs](https://github.com/bottlerocket-os/bottlerocket/blob/develop/PROVISIONING-METAL.md#network-interface-configuration).

For the `import.spec` being used, I believe you would need to change `IpAllocationPolicy` to be `fixedPolicy` like this:

```yaml
{
  "DiskProvisioning": "flat",
  "IPAllocationPolicy": "fixedPolicy",
  "IPProtocol": "IPv4",
  "NetworkMapping": [
    {
      "Name": "VM Network",
      "Network": ""
    }
  ],
  "MarkAsTemplate": false,
  "PowerOn": false,
  "InjectOvfEnv": false,
  "WaitForIP": false,
  "Name": null
}
```

Then follow [those `net.toml` instructions](https://github.com/bottlerocket-os/bottlerocket/blob/develop/PROVISIONING-METAL.md#network-interface-configuration) to configure your static addressing.

I will report back if I can find better instructions, but if you get a chance to try things out, it would be great to hear how it goes for you.

In either case, the docs definitely should be expanded to give better instructions here. Thanks for highlighting this gap.
