### ISSUE TITLE
host-ctr: setting img reg credentials for `public.ecr.aws` does not work

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket#2671]
**Image I'm using:**
Any bottlerocket image supporting `settings.container-registry.mirrors` and `settings.container-registry.credentials`

**What I expected to happen:**
`host-ctr` to use the provided registry credentials in `settings.container-registry.credentials` for `public.ecr.aws` when going through a configured private registry mirror.

**What actually happened:**
`host-ctr` tries to pull the public ECR image from through the prescribed registry mirror but without the specified registry credentials for `public.aws.ecr` which then causes the image pull to fail.

**How to reproduce the problem:**
With the following user-data:
```toml
[settings.container-registry.mirrors]
"public.ecr.aws" = ["https://198.18.34.118:443"]
[settings.pki.registry-mirror-ca]
data = "<redacted>"
trusted=true
[[settings.container-registry.credentials]]
registry = "public.ecr.aws"
username = "<redacted>"
password = "<redacted>"
```

Bottlerocket then repeatedly fails to pull `bottlerocket-admin` host container image from public ECR due to authentication failures.

<img width="1621" alt="Screen Shot 2022-12-15 at 4 06 14 PM" src="https://user-images.githubusercontent.com/52762042/208540249-cf3c4eed-3e47-4598-bc9c-325595452ef4.png">
