### ISSUE TITLE
aarch64 nodes fail to pull `eks/pause` during node init

### ISSUE THREAD

**Issue by pat-s** [bottlerocket-os/bottlerocket#2778]
**Image I'm using:**

bottlerocket-aws-k8s-1.24-aarch64-v1.12.0-6ef1139f

**What I expected to happen:**

Nodes are able to pull the `eks/pause` image and join the cluster.

**What actually happened:**

Nodes fail to pull the `eks/pause` image during the init container of the `aws-node` pod.

```
error: code = Unknown desc = failed to get sandbox image "602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/pause:3.1-eksbuild.1": failed to pull image "602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/pause:3.1-eksbuild.1": failed to pull and unpack image "602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/pause:3.1-eksbuild.1": failed to resolve reference "602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/pause:3.1-eksbuild.1": pulling from host 602401143452.dkr.ecr.eu-central-1.amazonaws.com failed with status code [manifests 3.1-eksbuild.1]: 401 Unauthorized 
```

**How to reproduce the problem:**

Create a ASG with a arm64 graviton instance (e.g. t4g) and the linked BR image.

**Additional information:**

- x86_64 nodes running `bottlerocket-aws-k8s-1.24-x86_64-v1.12.0-6ef1139f` and the exact same ASG configuration work fine
- arm64 graviton instances running AL2 (`amazon-eks-arm64-node-1.24-v20230127`) work fine
- I have reproduced the behavior multiple times now to make sure it's not an ASG or k8s issue
- The ASG group's IAM role has the `AmazonEC2ContainerRegistryReadOnly` attached
- EKS addons: 
  - CNI: v1.12.1-eksbuild.2
  - proxy: v1.24.9-eksbuild.1
  - DNS: v1.8.7-eksbuild.3

**Comment by zmrow** [comment]
Hi @pat-s !  I just attempted to reproduce this behavior in `eu-central-1` and couldn't!  (I chose that region because that was in the error message you pasted above)

I confirmed the AMI is the same as you are using: `ami-04ddbb09d9e7726b2` (`bottlerocket-aws-k8s-1.24-aarch64-v1.12.0-6ef1139f`)

I created a cluster using `eksctl` and the below config and both nodes came up and joined the cluster properly.  

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket-arm
  region: eu-central-1
  version: '1.24'

nodeGroups:
  - name: ng-bottlerocket
    instanceType: t4g.small
    desiredCapacity: 2
    amiFamily: Bottlerocket
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    ssh:
        allow: true
        publicKeyName: <MY KEY HERE>
    bottlerocket:
      settings:
        motd: "Hello from eksctl!"
```

Did you create this ASG by hand?  Can you confirm the above policies are attached to the IAM role?
