### ISSUE TITLE
`aws.profile` not respected in `ecr-credential-provider` template.

### ISSUE THREAD

**Issue by nairb774** [bottlerocket-os/bottlerocket#2885]
**Image I'm using:**

Bottlerocket OS 1.12.0 (aws-k8s-1.22)

**What I expected to happen:**

Using settings like the following should result in the `AWS_PROFILE` environment variable being set to `kubelet` within the `/etc/kubernetes/kubelet/credential-provider-config.yaml` file on the host. Additionally the desired role isn't being used for pulling images.

```toml
[settings.aws]
config = "W3Byb2ZpbGUga3ViZWxldF0KY3JlZGVudGlhbF9zb3VyY2UgPSBFYzJJbnN0YW5jZU1ldGFkYXRhCnJvbGVfYXJuID0gYXJuOmF3czppYW06OjEyMzQ1Njc4OTAxMjpyb2xlL015RXh0cmFSb2xlCg=="
profile = "kubelet"
region = "us-east-1"

[settings.kubernetes.credential-providers.ecr-credential-provider]
enabled = true
image-patterns = ["*.dkr.ecr.*.amazonaws.com"]
```

The expanded `settings.aws.config` is as follows:

```
[profile kubelet]
credential_source = Ec2InstanceMetadata
role_arn = arn:aws:iam::123456789012:role/MyExtraRole
```

**What actually happened:**

The credential helper file is missing the needed environment variable. This is the output as seen with the above configuration:

```
[root@admin]# cat /.bottlerocket/rootfs/etc/kubernetes/kubelet/credential-provider-config.yaml
apiVersion: kubelet.config.k8s.io/v1alpha1
kind: CredentialProviderConfig
providers:
  - name: ecr-credential-provider
    matchImages:
      - "*.dkr.ecr.*.amazonaws.com"
    defaultCacheDuration: "12h"
    apiVersion: credentialprovider.kubelet.k8s.io/v1alpha1
    env:
      - name: HOME
        value: /root
```

**How to reproduce the problem:**

Use the EKS BottlerocketOS image with the additional settings shown above to observe the incorrect configuration generation. Obviously the role referenced in the `kubelet` profile should exist with sufficient permissions to allow the instance role to assume it, and be useful for container image pulling. Given this looks to, at a minimum, just be a templating issue the whole setup might not be entirely necessary.
