### ISSUE TITLE
Dockerd-rootless does not start 

### ISSUE THREAD

**Issue by Alien2150** [bottlerocket-os/bottlerocket#2887]
**Image I'm using:**  ami-003e59b5f03f35661

Running a helm chart using docker:20.10-dind-rootless. I already checked out the solutions mentioned here: https://github.com/bottlerocket-os/bottlerocket/issues/1569 but I get this error when I try to run Dockerd inside bottlerocket:

```
exec rootlesskit \
--mtu="${DOCKERD_ROOTLESS_ROOTLESSKIT_MTU:-1500}" \
--disable-host-loopback \
--copy-up=/etc \
--copy-up=/run \
--port-driver=builtin \
--net="${DOCKERD_ROOTLESS_ROOTLESSKIT_NET:-vpnkit}" \
${DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS:-} \
"$@"


time="2023-03-13T13:23:00Z" level=warning msg="failed to mount sysfs, falling back to read-only mount: operation not permitted"
[rootlesskit:child ] error: creating tap tap0: ioctl: permission denied
```

I tried to adjust the capabilities ofc: 

```
securityContext:
  capabilities:
    add:
    - DAC_READ_SEARCH
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
  privileged: true
```

**What I expected to happen:**

**What actually happened:**

**How to reproduce the problem:**
