### ISSUE TITLE
Setup NVMe local disks for kubelet and containerd filesystem

### ISSUE THREAD

**Issue by Smana** [bottlerocket-os/bottlerocket#3207]
**What I'd like:**
Is it possible to setup NVMe disks when available in order to provide more IOPS to contained and kubelet filesystem.
I've been able to do that with AL2 using [this script](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bin/setup-local-disks)

Is there a way to do the same with bottlerocket?

**Comment by SmaineTF1** [comment]
The current node template used with karpenter

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  # Disabling for now because we need a script that setups local disks
  # amiFamily: Bottlerocket
  subnetSelector:
    karpenter.sh/discovery: ${environment}
  securityGroupSelector:
    karpenter.sh/discovery: ${cluster_name}
  blockDeviceMappings:
    # Root device
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 4Gi
        volumeType: gp3
        encrypted: true
  userData: |
    #!/bin/bash
    chmod +x /usr/bin/setup-local-disks
    /usr/bin/setup-local-disks raid0 --update
```

**Comment by Smana** [comment]
We ended up with this configuration

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  # Disabling for now because we need a script that setups local disks
  # amiFamily: Bottlerocket
  subnetSelector:
    karpenter.sh/discovery: ${environment}
  securityGroupSelector:
    karpenter.sh/discovery: ${cluster_name}
  blockDeviceMappings:
    # Root device
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 4Gi
        volumeType: gp3
        encrypted: true
  userData: |
    #!/bin/bash
    chmod +x /usr/bin/setup-local-disks
    /usr/bin/setup-local-disks raid0 --update
```
