### ISSUE TITLE
Not able to use sudo or su inside container deployed on EKS with bottlerocket as node AMI.

### ISSUE THREAD

**Issue by naveenbansalntnx** [bottlerocket-os/bottlerocket#3261]
**Image I'm using:** BottleRocket as the node AMI

**What I expected to happen:** The container image is built on top of centOS and it performs perfectly when using Amazon Linux or any other OS on EKS or self-managed K8s cluster. But on BottleRocket , I cannot execute sudo or su command inside container. The command just gets stuck . I have shared the strace logs below. 

**What actually happened:** Not able to use sudo or su. When executing sudo/su , the command just hangs with the following  recursive error  
>  *ppoll([{fd=5, events=POLLIN}], 1, NULL, NULL, 8) = ? ERESTARTNOHAND (To be restarted if no handler)*

**How to reproduce the problem:** It's a custom image, not shareable.
I have attached the logs for both commands and also a screenshot of bit of debugging if that helps. ( credits : stack-overflow as always 😀)

**Thanks in Advance !!**

<img width="818" alt="Screenshot 2023-07-13 at 9 37 55 PM" src="https://github.com/bottlerocket-os/bottlerocket/assets/86965468/07e62bd2-db64-42bd-a0de-c09de71a730d">

[strace su newuser.txt](https://github.com/bottlerocket-os/bottlerocket/files/12041405/strace.su.newuser.txt)
[strace sudo ls.txt](https://github.com/bottlerocket-os/bottlerocket/files/12041406/strace.sudo.ls.txt)

**Comment by etungsten** [comment]
Hi @naveenbansalntnx,

Can you describe how your pod is set up? Is there anything special about the deployment?

If you're able to get a shell on the host via the `admin-container` as described [here](https://github.com/bottlerocket-os/bottlerocket#admin-container), can you please check if there are any abnormal logs in `journalctl -u kubelet` or any AVC denial messages in `dmesg`?

I haven't been able to reproduce this error.
This is what I tried.
```
$ kubectl run centos --image=centos:latest --command -- sleep 5000000;
pod/centos created
$ kubectl exec --stdin --tty centos -- /bin/bash
[root@centos /]# sudo ls
bin  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
[root@centos /]# useradd test
[root@centos /]# su test
[test@centos /]$ whoami
test
[test@centos /]$ exit
exit
[root@centos /]# whoami
root
[root@centos /]# sudo ls
bin  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
[root@centos /]# su test
[test@centos /]$ sudo ls

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for test: 

```

**Comment by naveenbansalntnx** [comment]
Hi @etungsten , so the pod is running in a privileged mode , because I need host's disk access.
I tried centos normally , it works like you said .
So I tried various combinations and I was able to narrow down the issue. The problem arises when I mount the 

> /run/dbus/system_bus_socket

in my container. 

You can reproduce the error using the yaml config below .

I am attaching two yaml file. 

1. With bus socket - sudo will get stuck 
2. Without bus socket - It works fine.

[centos_with_socket.yml.txt](https://github.com/bottlerocket-os/bottlerocket/files/12045935/centos_with_socket.yml.txt)
[centos_without_socket.yml.txt](https://github.com/bottlerocket-os/bottlerocket/files/12045936/centos_without_socket.yml.txt)


But it's fine , I can work without it for now, but is it correct how I am passing disks using 

> /dev

folder . Because in bottle rocket I don't see any device under /dev directory.

**Comment by etungsten** [comment]
Bottlerocket's SELinux policy currently blocks container access to dbus. 

https://github.com/bottlerocket-os/bottlerocket/blob/0ddb80283e7785cee816069f4719d0a392c25d13/packages/selinux-policy/class.cil#L271

If you check `dbus-broker` logs on the host you'll see SElinux denial messages whenever you try to `su`/`sudo`/`useradd`. This is likely because CentOS distribution of these binaries link to libraries that make dbus queries.
From the `admin-container`:
```
[root@admin]# sudo sheltie                                                                                                                                                                                        
bash-5.1# journalctl --no-hostname -u dbus-broker -f
Jul 14 18:04:02 dbus-broker-launch[951]: avc:  denied  { send_msg } for  scontext=system_u:system_r:control_t:s0-s0:c0.c1023 tcontext=system_u:system_r:bus_t:s0 tclass=dbus permissive=0
Jul 14 18:04:02 dbus-broker[951]: A security policy denied :1.66 to send method call /org/freedesktop/DBus:org.freedesktop.DBus.Hello to org.freedesktop.DBus.
```

The workaround would be to add the `super_t` label to the container. Do note that this elevates container privileges to the highest level so please use this with care. You can read about this more in our security guidance in https://github.com/bottlerocket-os/bottlerocket/blob/develop/SECURITY_GUIDANCE.md#limit-use-of-privileged-selinux-labels.

An example manifest (extending the `centos_with_socket.yml` you provided) with the labels would look like,
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
    - name: centos
      image: centos
      securityContext:
        # SElinux labels won't apply if `privileged` is set to true
        allowPrivilegeEscalation: true
        capabilities:
          add:
          - SYS_ADMIN
        seLinuxOptions:
          user: system_u
          role: system_r
          type: super_t
          level: s0
      command:
        - sleep
        - infinity
      volumeMounts:
      - mountPath: /dev
        name: dev
      - mountPath: /run/udev/control
        name: udev
      - mountPath: /run/dbus/system_bus_socket
        name: dbus
        readOnly: true
  volumes:
    - name: dev
      hostPath:
        path: /dev
    - name: udev
      hostPath:
        path: /run/udev/control
    - name: dbus
      hostPath:
        path: /run/dbus/system_bus_socket
```

Regarding your question here:
> But it's fine , I can work without it for now, but is it correct how I am passing disks using `/dev` folder . Because in bottle rocket I don't see any device under /dev directory.

You might be checking in the `admin-container.  On the host filesystem after you `sudo sheltie`, all the devices should show up:
```
bash-5.1# ls /dev/
autofs	       cpu_dma_latency	hpet	      loop1  mapper  nvme0n1	 nvme0n1p3  nvme1      random	 stdout		  tty12  tty19	tty25  tty31  tty38  tty44  tty50  tty57  tty63  ttyS3	  vcsa1
block	       cuse		hugepages     loop2  mqueue  nvme0n1p1	 nvme0n1p4  nvme1n1    rtc	 termination-log  tty13  tty2	tty26  tty32  tty39  tty45  tty51  tty58  tty7	 uhid	  vcsu
btrfs-control  disk		input	      loop3  net     nvme0n1p10  nvme0n1p5  nvme1n1p1  rtc0	 tty		  tty14  tty20	tty27  tty33  tty4   tty46  tty52  tty59  tty8	 uinput   vcsu1
char	       dm-0		kmsg	      loop4  ng0n1   nvme0n1p11  nvme0n1p6  nvram      shm	 tty0		  tty15  tty21	tty28  tty34  tty40  tty47  tty53  tty6   tty9	 urandom  vfio
console        fd		log	      loop5  ng1n1   nvme0n1p12  nvme0n1p7  psaux      snapshot  tty1		  tty16  tty22	tty29  tty35  tty41  tty48  tty54  tty60  ttyS0  vcs	  vhost-net
core	       full		loop-control  loop6  null    nvme0n1p13  nvme0n1p8  ptmx       stderr	 tty10		  tty17  tty23	tty3   tty36  tty42  tty49  tty55  tty61  ttyS1  vcs1	  vhost-vsock
cpu	       fuse		loop0	      loop7  nvme0   nvme0n1p2	 nvme0n1p9  pts        stdin	 tty11		  tty18  tty24	tty30  tty37  tty43  tty5   tty56  tty62  ttyS2  vcsa	  zero
```
