### ISSUE TITLE
Rewrite shells scripts from xfsprogs in Rust

### ISSUE THREAD

**Issue by yeazelm** [bottlerocket-os/bottlerocket#3272]
**What I'd like:** 
Currently, the shells scripts normally found in xfsprogs are excluded from the build. These won't work as is in Bottlerocket since they rely upon a shell. I would still like this functionality in xfsprogs, so we should rewrite them in something like Rust to provide the same experience. Most of these scripts are simple argument parsing and passing to another xfs program so it shouldn't be a ton of work.

The priority in my opinion of these scripts is:
```
fsck.xfs
xfs_admin
xfs_info
xfs_mkfile
xfs_ncheck
xfs_bmap
xfs_freeze
xfs_metadump
```

**Any alternatives you've considered:**
Running the commands manually, for instance, `xfs_info /local` can be accomplished via `xfs_spaceman -p xfs_info -c info /local` but most users won't know this workaround and its a lot more work. I don't know if there are as great alternatives for things like `fsck.xfs`.

**Comment by arnaldo2792** [comment]
One of the concerns that folks had about the missing scripts were failures while using Persistent Volumes, in particular, calls to `fsck`. Depending on how the Persistent Volumes are configured, there is an execution path in the `kubelet` that executes `fsck` on a block device. I tried different scenarios to generate failures when using the `xfs` utils provided by the host. These include:

1. Disk is formatted as `xfs` and the PV is configured as `ext4`, a failure occurs since `fsck -a ext4` fails to run on the `xfs` partition
2. Disk is formatted as `xfs` and the PV is configured as `xfs`, nothing fails, `fsck -a xfs` runs
3. Disk isn't formatted, and the PV is configured with an unsupported format (e.g., `btrfs`), the mount fails
4. Path to the block device is used instead of the path to the `xfs` partition, and the PV is configured as `xfs`, `fsck -a xfs` fails since command fails to identify where is the partition.

This is the configuration file I used for my testing, the only value that I changed was `fsType`, to trigger specific failures:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /dev/disk/by-label/LOCAL_VOLUME
    fsType: xfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-192-168-93-143.us-west-2.compute.internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: example-pv-claim
  containers:
    - name: task-pv-container
      image: amazonlinux:2023
      command: ["sleep", "infinity"]
      volumeMounts:
        - mountPath: "/mnt/"
          name: task-pv-storage
```

I think it is safe to assume that the missing `fsck.xfs` won't cause any troubles at runtime, but still it will be nice to have the helper.
