### ISSUE TITLE
Should the bottlerocket containerd-config.toml file have discard_unpacked_layers set to true by default

### ISSUE THREAD

**Issue by pptb-aws** [bottlerocket-os/bottlerocket#3314]
**What I'd like:** discard_unpacked_layers to be enabled for containerd by default.

Please see [this issue](https://github.com/awslabs/amazon-eks-ami/issues/1359) in the default EKS AMI for full details and testing done in that AMI that should apply to Bottlerocket too.

I believe the containerd settings are [here](https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/containerd/containerd-config-toml_k8s_containerd_sock) for the default version and [here](https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/containerd/containerd-config-toml_k8s_nvidia_containerd_sock) for nvidia version.

**Any alternatives you've considered:**  This would require making a custom AMI as described in [this issue](https://github.com/bottlerocket-os/bottlerocket/issues/2408).

**Comment by stmcginnis** [comment]
Great suggestion @pptb-aws - thanks for raising this. I think we will need to do some experimenting and research to see how this behaves with things like shared base layers, reboots, and upgrades. As long as there are no bad side effects, I think it would be great to have this!

**Comment by maxsargentdev** [comment]
Please consider making this configurable when you make this change, there are projects that work based on this setting being disabled (https://github.com/spegel-org/spegel) and it may create a breaking change for people relying on the feature.

**Comment by ollie-kane-CB** [comment]
I'm just piping in here to mention Spegel as well.  Please make sure this is communicated if it's changed and how to preserve the existing behavior!

**Comment by kornelbicskei** [comment]
If anyone was wondering if this setting is exposed or not, it is, we set it with Bottlerocket userData:


        [plugins."io.containerd.grpc.v1.cri".containerd]
        # discard_unpacked_layers allows GC to remove layers from the content store after
        # successfully unpacking these layers to the snapshotter.
        discard_unpacked_layers = false

**Comment by lucasces** [comment]
> [plugins."io.containerd.grpc.v1.cri".containerd]
>     # discard_unpacked_layers allows GC to remove layers from the content store after
>     # successfully unpacking these layers to the snapshotter.
>     discard_unpacked_layers = false


I attempted to apply the previous userData to my Bottlerocket 1.34.0 nodes, but it was unsuccessful. Instead, I implemented an alternative approach that incorporates a bootstrap container and modifies the config.toml file using sed commands.

```toml
[settings.bootstrap-containers.set-discard-unpacked-layers]
  mode = "always"
  essential = false
  user-data = "IyEvYmluL2Jhc2gKZWNobyAiQWRkaW5nIGRpc2NhcmRfdW5wYWNrZWRfbGF5ZXJzIgpzZWQgLWkgJ3MvXFtwbHVnaW5zXC4iaW9cLmNvbnRhaW5lcmRcLmdycGNcLnYxXC5jcmkiXC5jb250YWluZXJkXF0vW3BsdWdpbnMuImlvLmNvbnRhaW5lcmQuZ3JwYy52MS5jcmkiLmNvbnRhaW5lcmRdXG5kaXNjYXJkX3VucGFja2VkX2xheWVycyA9IGZhbHNlLycgLy5ib3R0bGVyb2NrZXQvcm9vdGZzL2V0Yy9jb250YWluZXJkL2NvbmZpZy50b21s"
```

But it would be nice to have a official setting to control `discard_unpacked_layers`.

**Comment by yurrriq** [comment]
```toml
[plugins."io.containerd.grpc.v1.cri".containerd]
discard_unpacked_layers = false
```
in user data didn't work for me on Bottlerocket 1.39.1 either as it didn't end up in `/etc/containerd/config.toml`.
