### ISSUE TITLE
Garbage Collector don't work on the image disk

### ISSUE THREAD

**Issue by winnieoursbrun** [bottlerocket-os/bottlerocket#3350]
**Image I'm using:**
Bottlerocket OS 1.14.2 (aws-k8s-1.27)

**What I expected to happen:**
The garbage collector to use metrics from disk `/dev/xvdb` to check the threshold configured by this kubelet configuration `imageGCHighThresholdPercent` and `imageGCLowThresholdPercent `, and clean docker images if needed.

**What actually happened:**
Kubelet seem to check value from the the disk `dev/xvda`, the disk which contain system and it's not relevant to check. So the `xvdb` can be full and no garbage collection will be triggered.

**How to reproduce the problem:**
Setup a EKS node with bottlerocket and have a little disk size for `xvdb`, spawn a big size app, replace by a new big size image, and continue till disk is full.

**Karpenter config**
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 80Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
```

EDIT: here the good config:
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: bottlerocket
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 80Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
```

**Why this ticket in this repo ?**
I think it need to be in Karpenter repo, because i have this issue because i need to have two different disks for bottlerocket, and kubelet don't seem to handle it.

**Comment by yeazelm** [comment]
Hello @winnieoursbrun, thanks for cutting this issue! I noticed that your config you provided specifies the size for `/dev/xvda` at `80Gi` but that is the root volume which isn't where the images are stored. Bottlerocket won't utilize this disk size due to the layout of the disks: https://github.com/bottlerocket-os/bottlerocket#default-volumes. By default, the OS will put all images on `/dev/xdvb` (or `/dev/nvme1n1p1` on many instances). 

I tried setting a very aggressive GC threshold (10% low , 20% high) and filled up my disk with very large images. I see it garbage collecting these images back under the 20% on the second volume. Can you provide any logs from kublet showing if the garbage collection is failing or working? Something similar to this:

```
Aug 21 15:19:34 ip-192-168-91-225.us-west-2.compute.internal kubelet[3789814]: E0821 15:19:34.215014 3789814 kubelet.go:1400] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
Aug 21 19:44:35 ip-192-168-91-225.us-west-2.compute.internal kubelet[3789814]: E0821 19:44:35.145760 3789814 kubelet.go:1400] "Image garbage collection failed once. Stats initialization may not have completed yet" err="Failed to garbage collect required amount of images. Attempted to free 10331919974 bytes, but only found 513167194 bytes eligible to free."
Aug 21 19:49:36 ip-192-168-91-225.us-west-2.compute.internal kubelet[3789814]: E0821 19:49:36.694639 3789814 kubelet.go:1396] "Image garbage collection failed multiple times in a row" err="Failed to garbage collect required amount of images. Attempted to free 12766168678 bytes, but only found 2985726480 bytes eligible to free."

# or look at kubelet logs for "gc"
Aug 21 19:49:35 ip-192-168-91-225.us-west-2.compute.internal kubelet[3789814]: I0821 19:49:35.147189 3789814 image_gc_manager.go:323] "Disk usage on image filesystem is over the high threshold, trying to free bytes down to the low threshold" usage=26 highThreshold=20 amountToFree=12766168678 lowThreshold=10
Aug 21 19:49:35 ip-192-168-91-225.us-west-2.compute.internal kubelet[3789814]: I0821 19:49:35.150220 3789814 image_gc_manager.go:400] "Removing image to free bytes" imageID="sha256:aed6e2045b483bd00fb5c0174f7b85d714439099c67b0b0176a0097553ed9ac5" size=1297740849
Aug 21 19:49:35 ip-192-168-91-225.us-west-2.compute.internal kubelet[3789814]: I0821 19:49:35.737725 3789814 image_gc_manager.go:400] "Removing image to free bytes" imageID="sha256:9cb1125b36a64bfd66f3d69774c7fd9d43fcb0cb5df1405d249732ac4b4bf8bd" size=1687985631
```

Before the cleanup:
```
/dev/nvme1n1p1    79G   17G   62G  22% /local
```
After the cleanup:
```
/dev/nvme1n1p1    79G  7.9G   71G  10% /local
....
# I then launched more containers to keep it going and saw it increase again under the 20%
/dev/nvme1n1p1    79G   13G   67G  16% /local
```
As you can see, at first they failed but they eventually did succeed. I saw my disk usage spike to over 25% and then it was able to get it back down to about 10%.

**Comment by winnieoursbrun** [comment]
Hello @yeazelm !

Yes, sorry, i've put my AL2 Karpenter config, here the good one:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: bottlerocket
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 80Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
```

Thanks for testing and providing logs, i will share you this asap

**Comment by winnieoursbrun** [comment]
Hello @yeazelm !

I understood something after some try, i found the logs about garbage collecting, and it tried to do some garbage collection when the disk was full, but `Failed to garbage collect required amount of images. Attempted to free 37203380633 bytes, but only found 0 bytes eligible to free.` and that normal because every pod and every image on the node was useful.

I reproduce it with 40Gb of disk space. And i can have the /local full.

But i'd like to know, when /local is full, Kubelet don't set the node as **not** ready, with DiskPressure taint. Why ? Is this normal ? I'm not sure. The eviction of container should start no ?

Thank you for your time and patience !

PS: Can you confirm, `/local` is `rootfs` and we don't use `imagefs` ?

Here the Kubelet configuration of the node where i did my tests:
```yaml
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: 0.0.0.0
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
clusterDomain: cluster.local
clusterDNS:
- 172.20.0.10
evictionHard:
  memory.available: "5%"
kubeReserved:
  cpu: "90m"
  memory: "512Mi"
  ephemeral-storage: "1Gi"
kubeReservedCgroup: "/runtime"
systemReserved:
  memory: "512Mi"
systemReservedCgroup: "/system"
cpuCFSQuota: true
cpuManagerPolicy: none
podPidsLimit: 1048576
imageGCHighThresholdPercent: 20
imageGCLowThresholdPercent: 10
providerID: aws:///eu-central-1c/i-03ef9b6e1c0948ee3
resolvConf: "/run/netdog/resolv.conf"
hairpinMode: hairpin-veth
readOnlyPort: 0
cgroupDriver: systemd
cgroupRoot: "/"
runtimeRequestTimeout: 15m
featureGates:
  RotateKubeletServerCertificate: true
protectKernelDefaults: true
serializeImagePulls: false
seccompDefault: false
serverTLSBootstrap: true
tlsCipherSuites:
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
volumePluginDir: "/var/lib/kubelet/plugins/volume/exec"
maxPods: 58
staticPodPath: "/etc/kubernetes/static-pods/"
bash-5.1#
```

Here a `df -h` without the container disk mounted:
```
Filesystem       Size  Used Avail Use% Mounted on
/dev/root        904M  637M  205M  76% /
devtmpfs          16G     0   16G   0% /dev
tmpfs             16G     0   16G   0% /dev/shm
tmpfs            6.2G  8.5M  6.2G   1% /run
tmpfs             16G  496K   16G   1% /etc
tmpfs             16G  4.0K   16G   1% /etc/cni
tmpfs             16G     0   16G   0% /tmp
tmpfs             16G  8.0K   16G   1% /etc/containerd
tmpfs             16G   12K   16G   1% /etc/host-containers
tmpfs             16G     0   16G   0% /etc/kubernetes/pki/private
tmpfs             16G     0   16G   0% /root/.aws
tmpfs             16G     0   16G   0% /run/netdog
/dev/nvme1n1p1    40G   40G  266M 100% /local
/dev/nvme0n1p12   35M  1.3M   31M   4% /var/lib/bottlerocket
overlay           40G   40G  266M 100% /x86_64-bottlerocket-linux-gnu/sys-root/usr/lib/modules
overlay           40G   40G  266M 100% /opt/cni/bin
/dev/loop1       384K  384K     0 100% /x86_64-bottlerocket-linux-gnu/sys-root/usr/share/licenses
/dev/loop0        13M   13M     0 100% /var/lib/kernel-devel/.overlay/lower
overlay           40G   40G  266M 100% /x86_64-bottlerocket-linux-gnu/sys-root/usr/src/kernels
/dev/nvme0n1p3    29M   19M  7.2M  73% /boot
<CONTAINER MOUNTS....>
```

**Comment by stmcginnis** [comment]
Hi @winnieoursbrun - thanks for more details.

From your `kubelet.conf` contents, it looks like the only eviction setting you have is:

```yaml
evictionHard:
  memory.available: "5%"
```

I couldn't find an easy reference to see what the default values are for the `imagefs` thresholds, but based on the behavior you are seeing, I'm assuming that there is no default and it will just allow things to fill up unless configured otherwise.

I think what you need to pass in your configuration settings would be something along the lines of:

```toml
[settings.kubernetes.eviction-hard]
"imagefs.available" = "<10%"

[settings.kubernetes.eviction-soft]
"imagefs.available" = "<15%"

[settings.kubernetes.eviction-soft-grace-period]
"imagefs.available" = "30s"

[settings.kubernetes]
"eviction-max-pod-grace-period" = 40
```

From what I understand, those settings would mean that once the free space on the data volume gets to 15% or less, kubelet will wait for 40 seconds to see if it is just temporary. If the condition doesn't improve within those 40 seconds, it will then start evicting pods. Otherwise, if the space consumption gets to the point where there is less than 10% of the space left, it will not wait for any grace period and will immediately start evicting pods.

There are more details about what these settings mean in the [kubelet docs](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#eviction-thresholds).

I see you are using Karpenter for your node provisioning. I'm actually not too familiar with using karpenter, but I believe these settings would be passed using something like:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: bottlerocket-proxy
spec:
  amiFamily: Bottlerocket

  subnetSelector:
    karpenter.sh/discovery: mycluster

  securityGroupSelector:
    karpenter.sh/discovery: mycluster

  userData: |
    [settings.kubernetes.eviction-hard]
    "imagefs.available" = "<10%"

    [settings.kubernetes.eviction-soft]
    "imagefs.available" = "<15%"

    [settings.kubernetes.eviction-soft-grace-period]
    "imagefs.available" = "30s"

    [settings.kubernetes]
    "eviction-max-pod-grace-period" = 40
```

Hopefully that helps. If you get a chance, please try that out and let us know how it goes.

**Comment by winnieoursbrun** [comment]
Hi @stmcginnis - Thanks for informations.

I was pretty sure that Kubelet set default value when not specified in the `/etc/kubernetes/kubelet/config` file, as specified in https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

By the way, I've discovered with [this issue](https://github.com/aws/karpenter/issues/3722#issuecomment-1502026682), that there is missing support for some [kubelet options by Karpenter] (https://github.com/aws/karpenter/issues/3722#issuecomment-1502026682) with BottleRocket.
So that explain why i don't have the configuration i wanted in the kubelet.conf.

So i used the user-data to set the kubernetes configuration as you asked me to do, except i added more option and i didn't used `imagefs`, because we don't use a disk for images, we use the same disk as `nodefs`:
```yaml
    apiVersion: karpenter.k8s.aws/v1alpha1
    kind: AWSNodeTemplate
    metadata:
      name: bottlerocket
    spec:
      amiFamily: Bottlerocket
      blockDeviceMappings:
        - deviceName: /dev/xvdb
          ebs:
            volumeSize: 200Gi
            volumeType: gp3
            encrypted: true
            deleteOnTermination: true
      subnetSelector:
        karpenter.sh/discovery: ${var.cluster_name}
      securityGroupSelector:
        karpenter.sh/discovery: ${var.cluster_name}
      userData: |
        [settings.kubernetes.system-reserved]
        "cpu" = "100m"
        "memory" = "512Mi"
        "ephemeral-storage" = "1Gi"

        [settings.kubernetes.kube-reserved]
        "cpu" = "200m"
        "memory" = "512Mi"
        "ephemeral-storage" = "1Gi"

        [settings.kubernetes.eviction-hard]
        "memory.available" = "5%"
        "nodefs.available" = "10%"
        "nodefs.inodesFree" = "10%"

        [settings.kubernetes.eviction-soft]
        "memory.available" = "512Mi"
        "nodefs.available" = "15%"
        "nodefs.inodesFree" = "15%"

        [settings.kubernetes.eviction-soft-grace-period]
        "memory.available" = "10s"
        "nodefs.available" = "1m30s"
        "nodefs.inodesFree" = "2m"

        [settings.kubernetes]
        "eviction-max-pod-grace-period" = 40
        "image-gc-high-threshold-percent" = "90"
        "image-gc-low-threshold-percent" = "80"
```

With that, i'm expected to have the configuration on the node, but i have only theses:
```yaml
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
  memory.available: "5%"
  nodefs.available: "10%"
  nodefs.inodesFree: "10%"
kubeReserved:
  cpu: "200m"
  memory: "512Mi"
  ephemeral-storage: "1Gi"
systemReserved:
  cpu: "100m"
  ephemeral-storage: "1Gi"
  memory: "512Mi"
imageGCHighThresholdPercent: 90
imageGCLowThresholdPercent: 80
```
I removed useless parts which is not corresponding the user-data.

I don't get why with the user data i have only a part of what i want. I think i'm missing just a lil option.

BTW: The OS version changed since the opening of the issue, Karpenter updated to **Bottlerocket OS 1.15.0 (aws-k8s-1.27)** since the AMI release.

Thank you for your time !
