### ISSUE TITLE
Manually setting settings.kubernetes.max-pods will not work.

### ISSUE THREAD

**Issue by kahirokunn** [bottlerocket-os/bottlerocket#3463]
**Image I'm using:**
EKS 1.27 Managed Node Group

**What I expected to happen:**
I am using AWS EKS and do not have ENI on my pod because of the vxlan configuration.
Therefore, I am not caught in the limit of the number of ENIs that can be set per node.
This means that I can set up 100 containers on one small node.
Therefore, when I set max-pods = 100, the node will not start.

This is the settings file I actually used

```
[settings.kubernetes]
api-server = "https://yyyy.gr7.ap-northeast-1.eks.amazonaws.com"
cluster-certificate = "xxxxxxx"
cluster-name = "example"
max-pods = "100"
```

**What actually happened:**

max-pods is to reach 100 and start up.

**How to reproduce the problem:**

You can reproduce this by setting the following in userdata

```
[settings.kubernetes]
api-server = "https://yyyy.gr7.ap-northeast-1.eks.amazonaws.com"
cluster-certificate = "xxxxxxx"
cluster-name = "example"
max-pods = "100"
```

**Comment by stmcginnis** [comment]
Thanks for reporting this @kahirokunn. I believe this may be the same issue another user recently ran in to where managed node groups are also injecting its own `max-pods` value.

If you can take a look at https://github.com/bottlerocket-os/bottlerocket/issues/3449, that shows some steps for how to find the auto scaling group and launch template for your managed cluster. If you can look at the Advanced Details of the launch template, you can see the user data that is actually being used to launch the Bottlerocket instances. Can you check if there are two `max-pods` entries there - one for your 100 pod setting and one default one from MNG?

If so, this is the same issue. If you can open a support ticket with AWS, that behavior needs to be fixed in by Managed Node Groups as the service should not be providing its own `max-pods` setting.

If there are not two entries, please let me know. I will also try to reproduce this issue in my own cluster.

**Comment by stmcginnis** [comment]
I was not able to reproduce this. I used `eksctl` to create a managed node group while also overriding the `max-pods` value.

```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: br127
  region: us-east-2
  version: '1.27'
managedNodeGroups:
  - name: mng1
    instanceType: c5.xlarge
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    amiFamily: Bottlerocket
    labels: { role: br-worker }
    tags:
      nodegroup-type: Bottlerocket
    disableIMDSv1: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    bottlerocket:
      settings:
        motd: "Hello from eksctl!"
        kubernetes:
          max-pods: 100
```

The node group was created successfully. I double checked the launch template to see if it was similar to the other issue mentioned and see if it ended up adding a duplicate setting entry in the user data, but there was only the one line with my setting it to 100.

Checking the node state, it is reported as ready. It also reports the expected max pods value:

```sh
$ kubectl get nodes -o yaml | yq '.items[] | .metadata.name + "," + .status.capacity.pods'
ip-192-168-66-204.us-east-2.compute.internal,100
```

So my guess that this was related to the other issue seen appears to be incorrect, at least in my environment.

If your node doesn't complete initialization, then you probably won't be able to connect using SSM. You should be able to use the EC2 console to select the instance and Actions > Monitor and Troubleshoot > Get system log. That should show the output of the node initialization and should include whatever error it is encountering preventing it from fully initializing. That should hopefully give some clue as to what is causing problems in your environment.
