### ISSUE TITLE
Instances on k8s 1.26 image don't show up in SSM

### ISSUE THREAD

**Issue by Shershebnev** [bottlerocket-os/bottlerocket#3544]
Probably related to #3525 
I'm trying to follow this article https://aws.amazon.com/blogs/containers/reduce-container-startup-time-on-amazon-eks-with-bottlerocket-data-volume/ (code - https://github.com/aws-samples/containers-blog-maelstrom/blob/main/bottlerocket-images-cache/snapshot.sh), they have aws-k8s-1.24 image there as default - `/aws/service/bottlerocket/aws-k8s-1.24/x86_64/latest/image_id`, however given that my EKS cluster is on 1.26, I've tried to change the bottlerocket image to 1.26 respectively. With 1.24 everything works fine, instance appears in SSM almost immediately, but when switching to 1.26 it just never shows up in SSM (I've added also an instance name into CloudFormation stack as I've seen in some old issue that instances without names are skipped by SSM). I've also tried 1.25 - works fine, but 1.27 also never shows up

**Image I'm using:**
`bottlerocket-aws-k8s-1.26-x86_64-v1.15.1-264e294c` (latest for 1.26 currently)
`bottlerocket-aws-k8s-1.26-x86_64-v1.14.3-764e37e4` (tried an older one as well)

**What I expected to happen:**
Instance shows up in SSM

**What actually happened:**
It never shows up

**How to reproduce the problem:**
Original CF stack - https://github.com/aws-samples/containers-blog-maelstrom/blob/main/bottlerocket-images-cache/ebs-snapshot-instance.yaml
<details>
<summary>CF stack with my modifications (instance name and ebs volume size increased)</summary>

```  
AWSTemplateFormatVersion: 2010-09-09
Description: Bottlerocket instance to snashot data volume.

Parameters:
  AmiID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: "The ID of the AMI."
    Default: /aws/service/bottlerocket/aws-k8s-1.26-nvidia/x86_64/latest/image_id
  InstanceType:
    Type: String
    Description: "EC2 instance type to launch"
    Default: t2.small

Resources:
  BottlerocketInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiID
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref BottlerocketNodeInstanceProfile
      BlockDeviceMappings:
        - DeviceName: "/dev/xvdb"
          Ebs:
            VolumeType: "gp3"
            VolumeSize: "100"
            DeleteOnTermination: "true"
            Encrypted: "true"
      UserData:
        Fn::Base64: |
          [settings.host-containers.admin]
          enabled = true
      Tags:
        - Key: "Name"
          Value: "bottlerocket-snapshot-instance"
  BottlerocketNodeInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: "BottlerocketNodeRole"
  BottlerocketNodeRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                !Sub "ec2.${AWS::URLSuffix}"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"

Outputs:
  InstanceId:
    Value: !Ref BottlerocketInstance
    Description: Instance Id
```

</details>
Just the relevant parts of the original script from github link above:

```
CFN_STACK_NAME="Bottlerocket-ebs-snapshot"
INSTANCE_TYPE="g4dn.xlarge"
AMI_ID="/aws/service/bottlerocket/aws-k8s-1.26/x86_64/latest/image_id"
aws cloudformation deploy --stack-name $CFN_STACK_NAME --template-file ebs-snapshot-instance.yaml --capabilities CAPABILITY_NAMED_IAM \
--parameter-overrides AmiID=$AMI_ID InstanceType=$INSTANCE_TYPE
INSTANCE_ID=$(aws cloudformation describe-stacks --stack-name $CFN_STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='InstanceId'].OutputValue" --output text)


while [[ $(aws ssm describe-instance-information --filters "Key=InstanceIds,Values=$INSTANCE_ID" --query "InstanceInformationList[0].PingStatus" --output text) != "Online" ]]
do
   echo "waiting"
   sleep 5
done
```

When switching `1.26` to `1.24` or `1.25` everything works fine, but `1.27` also doesn't show up
Just in case, I've also tried cpu-only instances as well as NVidia version of the image

Since my purpose is to just use the data volume for docker images, should I just use 1.24/1.25 images?
