### ISSUE TITLE
Blockdevice mapping for data partiton

### ISSUE THREAD

**Issue by runningman84** [bottlerocket-os/bottlerocket#3613]
**What I'd like:**
I would like to use ephemeral instance store as a data parition.

In the AMI block device mapping it looks like bottlerocket has a root and a data volume.

I have not found any documentation how big each volume should be and what is the minimum size.

Will the data volume formated automatically and used? In this case a simple block device mapping like this would be enough:

`````
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 10Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    virtualName: "ephemeral0"
`````

**Any alternatives you've considered:**

I know that there are discussion like this: https://github.com/bottlerocket-os/bottlerocket/discussions/1991#discussioncomment-3265188

Due to the issues mentioned there I thought it might be even easier to just mount the whole volume instead of running these custom bootstrap containers.
