### ISSUE TITLE
SELinux blocks fanotify_mark from a Pod that has super_t type

### ISSUE THREAD

**Issue by slashben** [bottlerocket-os/bottlerocket#3677]
**Environment**

I am trying to use [Kubescape node agent](https://github.com/kubescape/node-agent) on a Botterocket node in a EKS cluster.

It failed with the error message:
```
{"level":"info","ts":"2023-12-17T08:19:09Z","msg":"credentials loaded","accountLength":36}                                         
W1217 08:19:09.532776  611945 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  T
time="2023-12-17T08:19:10Z" level=warning msg="container-hook: failed to fanotify mark: fanotify: mark error, permission denied"   
time="2023-12-17T08:19:10Z" level=warning msg="container-hook: failed to fanotify mark: fanotify: mark error, permission denied"   
{"level":"fatal","ts":"2023-12-17T08:19:10Z","msg":"error starting the container watcher","error":"setting up container collection:
```

I have checked the audit logs on the node and it is clear that SELinux blocks `fanotify_mark`:
```
MESSAGE=audit: type=1400 audit(1702795199.265:1601): avc:  denied  { watch_with_perm } for  pid=492743 comm="node-agent" path="/host/x86_64-bottlerocket-linux-gnu/sys-root/usr/bin/runc" dev="dm-0" ino=190 scontext=system_u:system_r:control_t:s0-s0:c0.c1023 tcontext=system_u:object_r:os_t:s0 tclass=file permissive=0
```

I have changed the securityContext of the daemonset to include:
```yaml
        securityContext:                                                                                                           
          capabilities:                                                                                                            
            add:                                                                                                                   
            - SYS_ADMIN                                                                                                            
            - SYS_PTRACE                                                                                                           
            - NET_ADMIN                                                                                                            
            - SYSLOG                                                                                                               
            - SYS_RESOURCE                                                                                                         
            - IPC_LOCK                                                                                                             
            - NET_RAW                                                                                                              
          privileged: true                                                                                                         
          runAsUser: 0                                                                                                             
          seLinuxOptions:                                                                                                          
            type: super_t  
```
to make sure this system-call is not denied by the SELinux engine.

**What I expected to happen:**

I expected this to work, according to the documentation `type: super_t` should bypass any restrictions.

**What actually happened:**

It is still blocked with the same audit message as above.

**How to reproduce the problem:**

Install Kubescape operator as explained [here](https://kubescape.io/docs/install-operator/#sizing-resources) on a Bottlerocket backed Kubernetes cluster.
