### ISSUE TITLE
"privileged: true" in pod spec clobbers SELinux options

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#3791]
**Image I'm using:**
`aws-k8s-1.28`

**What I expected to happen:**
I ran a pod with this security context:
```
securityContext:
  privileged: true
  seLinuxOptions:
    type: super_t
```

I expected the pod's process to have the `super_t` label on the running system.

**What actually happened:**
The pod's process had the `control_t` label instead.

**How to reproduce the problem:**
See above.

**Comment by bcressey** [comment]
This happens because the SELinux label is removed by containerd's CRI implementation [if the container is privileged](https://github.com/containerd/containerd/blob/b8654e36f49d44396c0acc4112c1cd15aabf25d8/internal/cri/server/podsandbox/sandbox_run.go#L124). This is similar to [how seccomp filters are treated](https://github.com/containerd/containerd/blob/b6ee1add7c47c7468db7b101e14499aae8e98141/internal/cri/server/podsandbox/container_linux.go#L44).

Normally this is fine since `privileged: true` implies "all the privileges" on most distros, just not on Bottlerocket.

The workaround is to avoid specifying `privileged: true` in the security context, and to instead list out everything that is implied by that:
```
securityContext:
  allowPrivilegeEscalation: true
  capabilities:
    add:
    - AUDIT_CONTROL
    - BLOCK_SUSPEND
    - DAC_READ_SEARCH
    - IPC_LOCK
    - IPC_OWNER
    - LEASE
    - LINUX_IMMUTABLE
    - MAC_ADMIN
    - MAC_OVERRIDE
    - NET_ADMIN
    - NET_BROADCAST
    - SYSLOG
    - SYS_ADMIN
    - SYS_BOOT
    - SYS_MODULE
    - SYS_NICE
    - SYS_PACCT
    - SYS_PTRACE
    - SYS_RAWIO
    - SYS_RESOURCE
    - SYS_TIME
    - SYS_TTY_CONFIG
    - WAKE_ALARM
  seccompProfile:
    type: Unconfined
  seLinuxOptions:
    type: super_t
```

This works unless the privileged container needs access to host devices. Right now, the device cgroup is set to [all devices allowed](https://github.com/containerd/containerd/blob/b8654e36f49d44396c0acc4112c1cd15aabf25d8/internal/cri/server/container_create.go#L714) for privileged containers, and there's no way to specify the equivalent in the pod spec without `privileged: true`.
