### ISSUE TITLE
Intermittent pod attach issues with bottlerocket-aws-k8s-1.24-x86_64-v1.19.3-f097c617 AMI

### ISSUE THREAD

**Issue by aaronborden-rivianvw** [bottlerocket-os/bottlerocket#3866]
**Image I'm using:**
AWS AMI bottlerocket-aws-k8s-1.24-x86_64-v1.19.3-f097c617 ami-08ab333430f1465ce
kublet version reported: v1.24.17-eks-bd4e8bf
Karpenter 0.30.0

We're using Bottlerocket to run our [GitLab Runner CI jobs](https://docs.gitlab.com/runner/executors/kubernetes/index.html). After the 1.19.3 AMI was released, we started seeing jobs hanging after pod start and eventually timing out on nodes deployed with the latest Bottlerocket image.

**What I expected to happen:**
Nodes running Bottlerocket 1.19.3 to perform similar to Bottlerocket 1.19.2 with respect to kubectl attach stability.

**What actually happened:**
We saw an increase in the number of failed jobs with error message.

> WARNING: prepare_script could not run to completion because the timeout was exceeded. For more control over job and script timeouts see: https://docs.gitlab.com/ee/ci/runners/configure_runners.html#set-script-and-after_script-timeouts
> ERROR: Job failed: execution took longer than 1h0m0s seconds

Note that this did not affect all jobs, the error was rare, but frequent enough for us to see it ~0.7% of jobs affected. We saw about 175 jobs fail with this error during an 8 hour period.

After reverting to Bottlerocket 1.19.2, the error went away.

**How to reproduce the problem:**
Unfortunately, I don't have a great method for reproduction. The gitlab-runner uses `attach` to run scripts within the build container, so perhaps you could simplify the repro by doing `kubectl attach` in a loop.

1. Specify Bottlerocket v1.19.3
2. Run many CI jobs

```yaml
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  amiSelector:
    aws::name: bottlerocket-aws-k8s-1.24-x86_64-v1.19.3-f097c617
    # ...
```
