### ISSUE TITLE
exec probes such as readiness and liveness probes time out in v1.19.3

### ISSUE THREAD

**Issue by evgeny-goldin** [bottlerocket-os/bottlerocket#3867]
**Image I'm using:**

We're using Karpenter on AWS EKS with K8s `1.28` and `amiFamily: Bottlerocket` in its `EC2NodeClass`. On Apr 2, shortly after Bottlerocket `v1.19.3` [was released](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.19.3) Karpenter was replacing nodes with the newer AMI and we started experiencing issues with Redis `StatefulSet` Pods ([redis-ha-server.yaml.txt](https://github.com/bottlerocket-os/bottlerocket/files/14876723/redis-ha-server.yaml.txt)) where it would take them up to 30 minutes to become `Ready`.

Redis containers `readiness` and `liveness` probes were timing out which would prevent the Pods from becoming `Ready`: 

```
2m34s       Warning   Unhealthy             pod/argocd-redis-ha-server-1         Readiness probe failed: command "sh -c /health/sentinel_liveness.sh" timed out
2m34s       Warning   Unhealthy             pod/argocd-redis-ha-server-1         Liveness probe failed: command "sh -c /health/redis_liveness.sh" timed out
```

```
5m10s       Warning   Unhealthy             pod/argocd-redis-ha-server-1         Readiness probe failed: command "sh -c /health/sentinel_liveness.sh" timed out
19m         Warning   Unhealthy             pod/argocd-redis-ha-server-1         Liveness probe failed: command "sh -c /health/redis_liveness.sh" timed out
20m         Warning   Unhealthy             pod/argocd-redis-ha-server-1         Liveness probe failed: command "sh -c /health/sentinel_liveness.sh" timed out
3m55s       Warning   Unhealthy             pod/argocd-redis-ha-server-1         Readiness probe failed: command "sh -c /health/redis_readiness.sh" timed out
```

.. but they would all work fine and respond immediately when executed manually: 

```
$ kshell argocd-redis-ha-server-1 -c sentinel -- sh
/data $ /health/sentinel_liveness.sh
response=PONG
```

```
<<K9s-Shell>> Pod: argocd/argocd-redis-ha-server-2 | Container: redis
/data $ /health/redis_liveness.sh
response=PONG
```

```
<<K9s-Shell>> Pod: argocd/argocd-redis-ha-server-0 | Container: redis
/data $ /health/redis_readiness.sh
response=PONG
```

These are `exec` probes:

```
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - /health/redis_readiness.sh

        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - /health/sentinel_liveness.sh

        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /health/redis_liveness.sh
```

Kubelet log (`journalctl -u kubelet`):

```
Apr 02 22:37:14 host-id kubelet[1415]: I0402 22:37:14.281492    1415 prober_manager.go:312] "Failed to trigger a manual run" probe="Readiness"
Apr 02 22:37:53 host-id kubelet[1415]: I0402 22:37:53.904724    1415 prober_manager.go:312] "Failed to trigger a manual run" probe="Readiness"
Apr 02 22:38:19 host-id kubelet[1415]: I0402 22:38:19.904879    1415 prober_manager.go:312] "Failed to trigger a manual run" probe="Readiness"
Apr 02 22:38:59 host-id kubelet[1415]: I0402 22:38:59.906768    1415 prober_manager.go:312] "Failed to trigger a manual run" probe="Readiness"
Apr 02 22:39:21 host-id kubelet[1415]: I0402 22:39:21.904654    1415 prober_manager.go:312] "Failed to trigger a manual run" probe="Readiness"
Apr 02 22:40:08 host-id kubelet[1415]: I0402 22:40:08.904519    1415 prober_manager.go:312] "Failed to trigger a manual run" probe="Readiness"
```

**What I expected to happen:**

I expect Redis `StatefulSet` Pods to start normally after Bottlerocket update from `1.19.2` to `1.19.3`

**What actually happened:**

It would take Redis `StatefulSet` Pods 15-30 minutes to pass the probes and become `Ready`.

Pinning down Karpenter AMI ID to `"ami-04dbe1faabf8ed7eb"` in the `us-west-2` AWS Region (`bottlerocket-aws-k8s-1.28-x86_64-v1.19.2-29cc92cc`) solved the problem and all Redis Pods have started normally. 

**How to reproduce the problem:**

**Comment by jessesuen** [comment]
In case anyone is wondering what the exec probes are doing, it simply invoke `redis-cli` to issue a localhost redis PING command:

```
$ cat /health/redis_readiness.sh
response=$(
  redis-cli \
    -a "${AUTH}" --no-auth-warning \
    -h localhost \
    -p 6379 \
    ping
)
if [ "$response" != "PONG" ] ; then
  echo "$response"
  exit 1
fi
echo "response=$response"
```

**Comment by rpkelly** [comment]
Thanks for the report! This seems similar #3866 reported yesterday. Could you please confirm if this is occurring consistently or intermittently?

**Comment by jessesuen** [comment]
Agree it seems similar to https://github.com/bottlerocket-os/bottlerocket/issues/3866.

It is intermittent. And weirdly, given enough time (30m), it the exec probe eventually succeeded. 

Other notes, the actual resource usage was nowhere near CPU or memory limits of the node. It was one of the first thing we checked since based on past experience, exec probes can easily fail if the node ran out of CPU cycles to actually execute the probe in a timely manner.

**Comment by bcressey** [comment]
Likely this: https://github.com/containerd/containerd/issues/10036

Let's try the repro case but 1.19.3 included the containerd 1.6.30 update so it lines up.

**Comment by bcressey** [comment]
Adjusted the title to reflect that the impact isn't Redis-specific in any way.

**Comment by rpkelly** [comment]
With the release of [Bottlerocket v1.19.4](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.19.4) the containerd issue should be addressed!

**Comment by evgeny-goldin** [comment]
Yeap, `v1.19.4` has this issue fixed - all Redis Pods are starting normally using Karpenter's `EC2NodeClass`:

```
spec:
    amiFamily: Bottlerocket
    amiSelectorTerms:
    - name: bottlerocket-aws-k8s-1.28-x86_64-v1.19.4*
      owner: "651937483462"
    - name: bottlerocket-aws-k8s-1.28-aarch64-v1.19.4*
      owner: "651937483462"
```
