### ISSUE TITLE
Cannot execute binaries stored in an NFS Server running on a Bottlerocket node

### ISSUE THREAD

**Issue by liam-mackie** [bottlerocket-os/bottlerocket#4116]
**Image I'm using:**
`Bottlerocket OS 1.20.4 (aws-k8s-1.30)`

**Context:**
We have some software that runs multiple pods for multiple stages in a pipeline. To be able to complete this dynamically and allow retries on specific steps, we spawn short-lived pods that connect to an NFS server running in-cluster for its ephemeral data. A typical installation would have the orchestrator and the NFS server to begin with. When the orchestrator receives a piece of work, it will:
* Create a subfolder in the NFS server, and download any required executables to it
* Spawn a pod, which runs the executables in the subfolder
* Once the pod has finished running, the subfolder gets removed

The NFS server is a simple variant of [this alpine server](https://github.com/OctopusDeploy/nfs-server-alpine).

**What I expected to happen:**
When running an NFS Server in a container in bottlerocket, you are able to execute files on the share from a mount in a different container.

**What actually happened:**
The `NFSD` process is denied `execute` access. This is exhibited in this AVC denial log:
```
Jul 26 01:20:06 ip-10-0-19-55.ap-southeast-2.compute.internal audit[2830356]: AVC avc:  denied  { execute } for  pid=2830356 comm="nfsd" name="bootstrapRunner" dev="nvme1n1p1" ino=151427631 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:data_t:s0:c432,c649 tclass=file permissive=0
```

From what I can tell, this is because the process is running as a `kernel` task, even though it's actually exposing data from a share from a container. My current line of thinking is that this is because it's a privileged container and actually hooking into the kernel-level support.  The `nfsd` processes have the `system_u:system_r:kernel_t:s0` SELinux context, and are _not_ children of the NFS server pod.

**What I've tried to do to work around the problem:**
I've attempted to work around this problem by using EFS rather than locally hosting, but when using access points and dynamically provisioned volumes, `chmod` commands get `permission denied`, which fails many scripts (and even `tar` in some cases).

**How to reproduce the problem:**
To reproduce the problem, you can create the resources I've added below in a Kubernetes cluster that is running Bottlerocket OS `1.20.4`. I have been doing this in an AWS EKS cluster.

You will be able to see the logs after running `logdog` from the admin container **in the node running the NFS server, not the nfs-client pod**. To run this reproduction, you will also need the NFS CSI driver, which you can install using helm:
```bash
helm upgrade --install --atomic \
--repo https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts \
--namespace kube-system \
--version v4.6.0 \
csi-driver-nfs \
csi-driver-nfs
```

If you deploy this outside of the `default` namespace, please adjust the server URL to instead point to the namespace you're deploying to - replace `nfs.default.svc.cluster.local` with `nfs.<your-namespace>.svc.cluster.local`.

### Resources:
**NFS Server**
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs
  serviceName: "nfs"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
                - amd64
      containers:
      - env:
        - name: SHARED_DIRECTORY
          value: /octopus
        - name: SYNC
          value: "true"
        image: octopusdeploy/nfs-server:1.0.1
        imagePullPolicy: IfNotPresent
        name: nfs-server
        ports:
        - containerPort: 2049
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /octopus
          name: octopus-volume
      restartPolicy: Always
      volumes:
      - emptyDir:
          sizeLimit: 10Gi
        name: octopus-volume
  updateStrategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: nfs
spec:
  clusterIP: None
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: 2049
  selector:
    app.kubernetes.io/name: nfs
  sessionAffinity: None
  type: ClusterIP
```

**PV/PVC**
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-10gi
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: nfs.default.svc.cluster.local
      share: /
    volumeHandle: nfs.default.svc.cluster.local/octopus##
  mountOptions:
  - nfsvers=4.1
  - lookupcache=none
  - soft
  - timeo=50
  - retrans=4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-10gi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
```

**Client Pod**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client
spec:
  selector:
    matchLabels:
      app: nfs-client
  template:
    metadata:
      labels:
        app: nfs-client
    spec:
      containers:
      - name: nfs-client
        image: alpine
        command: ["sh"]
        args: 
        - -c
        - 'echo "echo \"hello world\"" > /octopus/runme.sh && chmod +x /octopus/runme.sh && sh -c "/octopus/runme.sh"'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /octopus
          name: mount
      volumes:
      - name: mount
        persistentVolumeClaim:
          claimName: nfs-pvc-10gi```
