### ISSUE TITLE
control the the cuda toolkit/nvidia drivers while picking images

### ISSUE THREAD

**Issue by eladmotola** [bottlerocket-os/bottlerocket#4164]
**What I'd like:**
I am using Karpenter with EKS to auto-update my os.
is there any way to control the Nvidia drivers/cuda toolkit you install?
I mean, I don't want to come up in the morning to figure out that someone upgraded those things without me knowing.
for example - I can see in the AWS marketplace that the image of bottlerocket called `amazon/bottlerocket-aws-k8s-1.29-nvidia-x86_64-v1.20.5-a3e8bda1`. I can't tell from the image which cuda or Nvidia drivers exists

I would like to do something like:
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: ${local.streamer_node_class_name}
spec:
  # Required, resolves a default ami and userdata
  amiFamily: Bottlerocket

  amiSelectorTerms:
    - name: "bottlerocket-aws-k8s-1.29-nvidia-x86_64-535-183-01-v12.1-*"
  ```

I understand that it's not possible to have a release for each cuda/nvidia drivers out there. but since you support this(and many thanks for that) can we make it less dangerous?

**Any alternatives you've considered:**
