### ISSUE TITLE
io_uring regression in 6.1 kernel

### ISSUE THREAD

**Issue by arnaldo2792** [bottlerocket-os/bottlerocket#4308]
**What happened?**

The latest Linux 6.1 kernel introduced a regression in applications using the `io_uring` syscalls, which could result in processes hanging and not being killed. In particular, `nodejs` applications seem susceptible to this regression (see https://github.com/amazonlinux/amazon-linux-2023/issues/840 for details).

**Affected versions**

Bottlerocket 1.27.1 variants using the 6.1 kernel:

* `aws-k8s-1.28*`
* `aws-k8s-1.29*`
* `aws-k8s-1.30*`
* `aws-k8s-1.31*`
* `vmware-k8s-1.28*`
* `vmware-k8s-1.29*`
* `vmware-k8s-1.30*`
* `vmware-k8s-1.31*`

**Comment by arnaldo2792** [comment]
**Workaround for nodejs applications**

Set the [`UV_USE_IO_URING=0`](https://nodejs.org/docs/latest-v21.x/api/cli.html#uv_use_io_uringvalue) environment variable in your affected workloads:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: <>
spec:
  selector:
    matchLabels:
      name: <>
  template:
    metadata:
      labels:
        name: <>
    spec:
      containers:
      - name: <>
        image: <>:<>
        #...
        env:
          - name: UV_USE_IO_URING
            value: '0'
```
