### ISSUE TITLE
Requesting ability to set headers and sources in container-registry settings API

### ISSUE THREAD

**Issue by houstonj1** [bottlerocket-os/bottlerocket#4437]
**What I'd like:**

We are attempting to use [Dragonfly](https://d7y.io/) with Bottlerocket nodes our EKS environment

We'd like to be able to create the files required by Dragonfly in `/etc/containerd/certs.d/<registry-host>.toml`

For example:
1. Addition to containerd configuration toml
```toml
[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/etc/containerd/certs.d"
```

2. For each registry added:

File `/etc/containerd/certs.d/<registry-host>.toml`
```toml
server = "https://<registry-host>"

[host."http://127.0.0.1:4001"]
capabilities = ["pull", "resolve"]

[host."http://127.0.0.1:4001".header]
X-Dragonfly-Registry = "https://<registry-host>"
```

Is this a possibility? Or are we thinking about these settings the correct way?

**Any alternatives you've considered:**

I didn't see any directly related issues or PRs. We're investigating using bootstrap containers to add / modify these files.
