### ISSUE TITLE
Bottlerocket image gives ephemeral storage errors on migrating from AL2023 on EKS

### ISSUE THREAD

**Issue by rohan-changejar** [bottlerocket-os/bottlerocket#4542]
**Image I'm using:**
Bottlerocket OS 1.39.0 (aws-k8s-1.32)

**What I expected to happen:**

Smooth migration from AL2023 to Bottlerocket OS without any hiccups. On lower environments, we were seeing stable performance.

**What actually happened:**
We begun getting this error 
`The node was low on resource: ephemeral-storage. Threshold quantity: 3170846026, available: 2914572Ki. Container api was using 28368Ki, request is 0, has larger consumption of ephemeral-storage. `
This is on the same configuration we were using the AL2023 image with.
This is causing multiple pods of a deployment to go into failed state.

Seeing these errors continuously 

<img width="1205" alt="Image" src="https://github.com/user-attachments/assets/d991a6f5-b709-4d9a-8022-de38030f82d1" />

**How to reproduce the problem:**
Migrate to the above mentioned bottlerocket image. We did the migration by specifying the new image version on the karpenter node class.

**Comment by koooosh** [comment]
Thanks for raising this issue, @rohan-changejar !

A few clarification questions:
1. What are the sizes of the ephemeral volumes you're using?
2. Can you show how you've set up the volumes?

**Comment by Shreyank031** [comment]
Hi @koooosh ,
We have set up volumes in node level, i.e using ec2nodeclass karpenter

### ec2nodeclass
```yaml
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 250Gi
      volumeType: gp3
  detailedMonitoring: true
```

Found out that we are suppose to define two distinct volumes, OS volume and Data volume for **Bottlerocket**

```yaml
spec:
  blockDeviceMappings:
    # Root device
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 40Gi
        volumeType: gp3
        encrypted: true
    # Data device: Container resources such as images and logs
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 200Gi
        volumeType: gp3
        encrypted: true

```

We never tried it after that, was waiting for the reply. 
Thanks
