### ISSUE TITLE
Java JVM does not respect Kubernetes pod memory limits on Bottlerocket 1.39.x

### ISSUE THREAD

**Issue by QuentinBtd** [bottlerocket-os/bottlerocket#4549]
## Java JVM does not respect Kubernetes pod memory limits on Bottlerocket (cgroups v2)

**Description:**  
I recently upgraded my EKS cluster from version 1.32 to 1.33, and at the same time I also updated my nodes to use Bottlerocket 1.39.1 (instead of 1.35.0).

When running Java (tested with 17 and 21) in a Kubernetes pod on Bottlerocket nodes, the JVM does not respect the pod’s memory limits for heap calculation. Instead, it appears to use the node’s total memory, which can lead to OOM errors. 
**With BR 1.35.0 and EKS 1.32 there was no problem.**

---

### Steps to reproduce

1. **Environment:**
   - EKS Kubernetes version: 1.33
   - Node OS: Bottlerocket 1.39.1
   - Java version: corretto 21
   - Pod manifest example:
     ```yaml
      apiVersion: v1
      kind: Pod
      spec:
        containers:
          - name: corretto
            image: "amazoncorretto:21.0.6-al2023-headless"
            imagePullPolicy: "IfNotPresent"
            resources:
              limits:
                memory: 2Gi
                cpu: 1
              requests:
                memory: 1Gi
                cpu: 1
            command:
              - "/bin/sh"
              - "-c"
            args:
              - "cat"
     ```

2. **Observed behavior:**
   - Started a pod with the above memory limit and Java 21.
   - No explicit `-Xmx` or heap options, only default container support.
   - Attached to the pod then ran:
     ```shell
        java -XshowSettings:vm -version
     ```
   - Output:
     ```
     Memory Limit: 2.00G
     Max. Heap Size (Estimated): 15.47G (On a 16Gio node)
     ```
     (Heap size is much larger than the pod limit.)

3. **Expected behavior:**
   - The JVM should set the max heap size as a percentage of the pod’s memory limit (e.g., ~512M for 2Gi with default settings).

4. **Additional tests:**
   - Ran the same pod and Java image on an Amazon Linux 2023 node (same Kubernetes version).
   - On Amazon Linux 2023, the JVM correctly detects and respects the pod memory limit for heap calculation.
   - Ran with `-XX:+UseContainerSupport -XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=50.0` java options. Same behavior. 

5. **Other notes:**
   - Tested with and without `-XX:+UseContainerSupport` and with Corretto 21 images.
   - Issue persists regardless of JVM options.
   - Bottlerocket nodes use cgroups v2 by default.

---

**Summary:**  
On Bottlerocket, the JVM detects the pod’s memory limit (`Memory Limit: 2.00G` is shown), but does not use it for heap calculation, resulting in a much larger heap than allowed by the pod. This issue does not occur on Amazon Linux 2023.

Please let me know if you need further details or logs.  
Thank you!

**Comment by KCSesh** [comment]
Hey @QuentinBtd

Thanks for bringing this to our attention. It looks like there are a few bugs here. 

OpenJDK has several related cgroupv2 upstream issues which can be seen here: 

* https://bugs.openjdk.org/browse/JDK-8348566
* https://bugs.openjdk.org/browse/JDK-8349988
* https://bugs.openjdk.org/browse/JDK-834781

I was able to reproduce the issue on Bottlerocket 1.39.1 using the pod you provided: 

```
 apiVersion: v1
 kind: Pod
 metadata:
  name: corretto-pod-1-39-1
 spec:
   containers:
     - name: corretto
       image: "amazoncorretto:21.0.6-al2023-headless"
       imagePullPolicy: "IfNotPresent"
       resources:
         limits:
           memory: 2Gi
           cpu: 1
         requests:
           memory: 1Gi
           cpu: 1
       command:
         - "/bin/sh"
         - "-c"
       args:
         - "tail -f /dev/null"
```
With the following output:

```
sh-5.2# java -XshowSettings:vm -version
VM settings:
    Max. Heap Size (Estimated): 3.83G
    Using VM: OpenJDK 64-Bit Server VM
```

And we can see cgroups v2 is not being detected:

```
sh-5.2# java -Xlog:os+container=trace --version
[0.000s][trace][os,container] OSContainer::init: Initializing Container Support
[0.000s][debug][os,container] Detected optional pids controller entry in /proc/cgroups
[0.000s][debug][os,container] controller cpu is not enabled

[0.000s][debug][os,container] One or more required controllers disabled at kernel level.
openjdk 21.0.6 2025-01-21 LTS
OpenJDK Runtime Environment Corretto-21.0.6.7.1 (build 21.0.6+7-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.6.7.1 (build 21.0.6+7-LTS, mixed mode, sharing)
sh-5.2#
```
