### ISSUE TITLE
Updater exits non-zero when passed flag to reboot

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket#864]
**Image I'm using:**

Updating `aws-k8s-v0.3.0` to `aws-k8s-v0.3.1`.

**What I expected to happen:**

I expected that the [Bottlerocket update operator](https://github.com/bottlerocket-os/bottlerocket-update-operator) would be able to call the host's updater executable - `updog` - to apply, switch to, and reboot to an update and observe a successful exit status. The update operator expects that the updater will exit with a zero status whenever it has successfully applied or performed the requested action (and a non-zero when an error is encountered).

**What actually happened:**

Sometimes\* when the update operator calls `updog` to apply the update and reboot, the executed `updog` gets sent a `SIGTERM` by the `init` system as it begins to kill process trees. Because `updog` does not handle the `SIGTERM` it exits non-zero and the update operator reports that its updater process (`updog`) failed to flip and reboot to the updated partition. This error causes the update operator agent and controller to leave a node cordoned off from the cluster.

This was observed and reported in https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/28

\*: I see this behavior approximately 20% of the time in a cluster of 16.

**How to reproduce the problem:**

Use a cluster that upgrades from `v0.3.0` to `v0.3.1` and the [Bottlerocket update operator deployment](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/7fcaf306d983df8542bb31bcad68a9142cde82cf/update-operator.yaml). I used the following `ClusterConfig` for `eksctl` and used a image built from the `v0.3.0` tag to upgrade from.

``` yaml
# v0.3.0 repro cluster
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: brupop
  region: us-west-2
  version: '1.15'

nodeGroups:
  - name: launched-as--0-3-0
    instanceType: m5.large
    desiredCapacity: 16
    amiFamily: Bottlerocket
    # Private AMI built from v0.3.0 in us-west-2
    ami: ami-ffffffffffffffff
    labels:
      "bottlerocket.aws/platform-version": "1.0.0"
    ssh:
      allow: true
      publicKeyName: my-key
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
```

I used the ASG that `eksctl` created to make passes at reproducing this issue:

``` shell
# Update to scale in and out for getting dead nodes:
aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$ASG_NAME" --min-size 0

# Then scale in and out as needed to observe:
#
# Scale in:
aws autoscaling set-desired-capacity --auto-scaling-group-name "$ASG_NAME" --desired-capacity 0
# Scale out:
aws autoscaling set-desired-capacity --auto-scaling-group-name "$ASG_NAME" --desired-capacity 16
```
