### ISSUE TITLE
containerd logs a lot of output with low value

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#872]
**Image I'm using:**
aws-k8s-1.15-x86_64-0.3.1

**What I expected to happen:**
System journal not to fill up low value information.

**What actually happened:**
System journal filled with lines like this repeated every five seconds:
```
containerd[3062]: time="2020-03-26T16:32:10.954615655Z" level=info msg="ExecSync for \"8f76a5ea2288727801a8fe780dabb06ce70f5490eb74c25a2207f25b1e91f905\" with command [/app/grpc-health-probe -addr=:50051] and timeout 1 (s)"
containerd[3062]: time="2020-03-26T16:32:11.023213140Z" level=info msg="Finish piping \"stdout\" of container exec \"7ca0ac98f8e733cbeedea4d7a6cce81885e9782c0f1b1b0830d4b43422b27117\""
containerd[3062]: time="2020-03-26T16:32:11.023213284Z" level=info msg="Finish piping \"stderr\" of container exec \"7ca0ac98f8e733cbeedea4d7a6cce81885e9782c0f1b1b0830d4b43422b27117\""
containerd[3062]: time="2020-03-26T16:32:11.023405191Z" level=info msg="Exec process \"7ca0ac98f8e733cbeedea4d7a6cce81885e9782c0f1b1b0830d4b43422b27117\" exits with exit code 0 and error <nil>"
containerd[3062]: time="2020-03-26T16:32:11.024190117Z" level=info msg="ExecSync for \"8f76a5ea2288727801a8fe780dabb06ce70f5490eb74c25a2207f25b1e91f905\" returns with exit code 0"
```

**How to reproduce the problem:**
Start a node, leave it running with a pod that has a health check configured.

**Comment by webern** [comment]
I'll see if there is a way to change the verbosity.

**Comment by webern** [comment]
I guess it's coming from the aws VPC CNI:
https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.6/config/v1.6/aws-k8s-cni.yaml

```yaml
      containers:
        - image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.6.0
          imagePullPolicy: Always
          ports:
            - containerPort: 61678
              name: metrics
          name: aws-node
          readinessProbe:
            exec:
              command: ["/app/grpc-health-probe", "-addr=:50051"]
            initialDelaySeconds: 35
          livenessProbe:
            exec:
              command: ["/app/grpc-health-probe", "-addr=:50051"]
            initialDelaySeconds: 35
          env:
            - name: AWS_VPC_K8S_CNI_LOGLEVEL
              value: DEBUG
            - name: AWS_VPC_K8S_CNI_VETHPREFIX
              value: eni
            - name: AWS_VPC_K8S_CNI_MTU
              value: "9001"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
```

In particular the value `DEBUG` probably needs to be set to `WARN`. I'll try to find out more about this.
